/* =====================================================================
   YEAR OH YEAR — EVENT LIST (1797 events)
   Format: [year, "description"]
   Negative years are BC (e.g. -490 = 490 BC). There is no year 0.
   To add an event: copy a line, change the year and text.
   Keep descriptions free of clues that give the year away.
   ===================================================================== */
const EVENTS = [

  // ---- Ancient world (BC) ----
  [-3100, "Narmer traditionally unifies Upper and Lower Egypt (approximately)"],
  [-2560, "The Great Pyramid of Giza is completed (approximately)"],
  [-2334, "Sargon of Akkad begins his reign, founding the first great Mesopotamian empire (approximately)"],
  [-1754, "Hammurabi's law code is inscribed in Babylon (approximately)"],
  [-1323, "The boy pharaoh Tutankhamun dies (approximately)"],
  [-1274, "Ramesses II fights the Hittites at the Battle of Kadesh"],
  [-1258, "Egypt and the Hittites sign the first known peace treaty (approximately)"],
  [-1184, "Traditional date of the fall of Troy"],
  [-1177, "Ramesses III repels the Sea Peoples (approximately)"],
  [-814, "Traditional date of the founding of Carthage"],
  [-776, "The first recorded Olympic Games are held at Olympia"],
  [-753, "Traditional date of the founding of Rome by Romulus"],
  [-722, "Assyria destroys the northern Kingdom of Israel"],
  [-701, "Sennacherib of Assyria besieges Jerusalem"],
  [-689, "Sennacherib sacks Babylon"],
  [-612, "Nineveh, capital of Assyria, falls to Babylonians and Medes"],
  [-594, "Solon becomes archon of Athens and reforms its laws"],
  [-586, "Nebuchadnezzar II destroys Jerusalem and the First Temple (approximately)"],
  [-560, "Croesus becomes king of Lydia (approximately)"],
  [-550, "Cyrus the Great overthrows the Median king Astyages"],
  [-546, "Cyrus the Great conquers Lydia and captures Croesus"],
  [-539, "Cyrus the Great captures Babylon"],
  [-529, "Cyrus the Great dies"],
  [-525, "Cambyses II of Persia conquers Egypt at the Battle of Pelusium"],
  [-522, "Darius I seizes the Persian throne"],
  [-514, "Harmodius and Aristogeiton assassinate Hipparchus in Athens"],
  [-509, "The Roman Republic is founded after the last king is expelled"],
  [-508, "Cleisthenes introduces democratic reforms in Athens"],
  [-499, "The Ionian Revolt against Persia begins"],
  [-494, "The Persians destroy Miletus after the Battle of Lade"],
  [-490, "The Athenians defeat the Persians at the Battle of Marathon"],
  [-486, "Darius I of Persia dies"],
  [-480, "Leonidas and his Spartans make their stand at Thermopylae"],
  [-479, "The Greeks defeat the Persians at the Battle of Plataea"],
  [-478, "The Delian League is founded under Athenian leadership"],
  [-470, "Socrates is born in Athens (approximately)"],
  [-462, "Ephialtes strips the Areopagus of its powers in Athens"],
  [-451, "The Twelve Tables of Roman law are drawn up (approximately)"],
  [-449, "The Peace of Callias ends the Greco-Persian Wars (traditional)"],
  [-447, "Construction of the Parthenon begins"],
  [-431, "The Peloponnesian War breaks out between Athens and Sparta"],
  [-430, "Plague strikes Athens"],
  [-429, "Pericles dies of the plague in Athens"],
  [-425, "Athens captures Spartan hoplites at Sphacteria"],
  [-421, "The Peace of Nicias brings a pause to the Peloponnesian War"],
  [-415, "Athens launches its disastrous Sicilian Expedition"],
  [-413, "The Athenian army is destroyed at Syracuse"],
  [-405, "Lysander destroys the Athenian fleet at Aegospotami"],
  [-404, "Athens surrenders to Sparta, ending the Peloponnesian War"],
  [-401, "Xenophon's Ten Thousand fight at the Battle of Cunaxa"],
  [-399, "Socrates is tried in Athens and sentenced to death"],
  [-390, "The Gauls sack Rome after the Battle of the Allia (traditional)"],
  [-387, "Plato founds the Academy in Athens (approximately)"],
  [-384, "Aristotle is born in Stagira"],
  [-371, "Thebes shatters Spartan power at the Battle of Leuctra"],
  [-362, "Epaminondas is killed at the Battle of Mantinea"],
  [-359, "Philip II becomes king of Macedon"],
  [-356, "Alexander the Great is born in Pella"],
  [-347, "Plato dies in Athens"],
  [-338, "Philip II of Macedon defeats Athens and Thebes at Chaeronea"],
  [-336, "Philip II of Macedon is assassinated"],
  [-335, "Alexander the Great razes Thebes"],
  [-334, "Alexander wins his first victory over Persia at the Granicus"],
  [-333, "Alexander defeats Darius III at the Battle of Issus"],
  [-332, "Alexander takes Tyre after a seven-month siege"],
  [-331, "Alexander the Great defeats Darius III at Gaugamela"],
  [-330, "Darius III is murdered by his own satrap Bessus"],
  [-326, "Alexander defeats King Porus at the Battle of the Hydaspes"],
  [-323, "Alexander the Great dies in Babylon"],
  [-322, "Aristotle dies"],
  [-322, "Demosthenes takes poison rather than surrender to Macedon"],
  [-321, "The Romans are humiliated at the Caudine Forks"],
  [-312, "Construction of the Via Appia begins"],
  [-305, "Ptolemy I declares himself king of Egypt"],
  [-301, "The Battle of Ipsus decides the fate of Alexander's empire"],
  [-280, "Pyrrhus of Epirus defeats the Romans at Heraclea"],
  [-279, "Pyrrhus wins a costly victory at Asculum"],
  [-275, "Rome defeats Pyrrhus at the Battle of Beneventum"],
  [-264, "The First Punic War between Rome and Carthage begins"],
  [-260, "Rome wins its first great naval victory at Mylae"],
  [-241, "Rome wins the First Punic War at the Aegates Islands"],
  [-221, "Qin Shi Huang unifies China and declares himself First Emperor"],
  [-218, "Hannibal leads his army and elephants across the Alps"],
  [-216, "Hannibal annihilates a Roman army at the Battle of Cannae"],
  [-212, "Archimedes is killed as Rome captures Syracuse"],
  [-207, "Hasdrubal is defeated and killed at the Metaurus"],
  [-202, "Scipio Africanus defeats Hannibal at the Battle of Zama"],
  [-197, "Rome defeats Philip V of Macedon at Cynoscephalae"],
  [-190, "Rome defeats Antiochus III at Magnesia (approximately)"],
  [-183, "Hannibal takes poison in exile (approximately)"],
  [-168, "Rome crushes Macedon at the Battle of Pydna"],
  [-167, "The Maccabean Revolt against the Seleucids begins"],
  [-146, "Rome destroys Carthage at the end of the Third Punic War"],
  [-146, "Rome destroys Corinth"],
  [-133, "Tiberius Gracchus is murdered in Rome"],
  [-121, "Gaius Gracchus dies during violence in Rome"],
  [-107, "Gaius Marius is elected consul for the first time"],
  [-106, "Cicero is born"],
  [-105, "The Cimbri destroy two Roman armies at Arausio"],
  [-102, "Marius destroys the Teutones at Aquae Sextiae"],
  [-100, "Julius Caesar is born"],
  [-91, "The Social War between Rome and its Italian allies begins"],
  [-88, "Sulla marches on Rome with his army"],
  [-82, "Sulla becomes dictator of Rome"],
  [-73, "Spartacus leads a slave revolt against Rome"],
  [-71, "Crassus crushes the slave revolt of Spartacus"],
  [-70, "The poet Virgil is born"],
  [-67, "Pompey clears the Mediterranean of pirates"],
  [-65, "The poet Horace is born"],
  [-63, "Cicero exposes the Catiline conspiracy"],
  [-63, "Octavian, the future Augustus, is born"],
  [-63, "Pompey captures Jerusalem"],
  [-60, "Caesar, Pompey and Crassus form the First Triumvirate"],
  [-58, "Julius Caesar begins his conquest of Gaul"],
  [-55, "Julius Caesar makes his first expedition to Britain"],
  [-54, "Caesar's second expedition to Britain"],
  [-53, "Crassus is killed after defeat by the Parthians at Carrhae"],
  [-52, "Caesar defeats Vercingetorix at the Siege of Alesia"],
  [-49, "Julius Caesar crosses the Rubicon"],
  [-48, "Caesar defeats Pompey at the Battle of Pharsalus"],
  [-48, "Pompey is murdered on landing in Egypt"],
  [-47, "Caesar defeats Pharnaces at Zela: 'I came, I saw, I conquered'"],
  [-45, "The Julian calendar comes into effect"],
  [-44, "Julius Caesar is assassinated on the Ides of March"],
  [-43, "Cicero is executed on Mark Antony's orders"],
  [-43, "Octavian, Antony and Lepidus form the Second Triumvirate"],
  [-43, "The poet Ovid is born"],
  [-42, "Brutus and Cassius are defeated at Philippi"],
  [-37, "Herod the Great takes control of Jerusalem"],
  [-31, "Octavian defeats Antony and Cleopatra at the Battle of Actium"],
  [-30, "Cleopatra dies and Egypt becomes a Roman province"],
  [-27, "Octavian is granted the title Augustus by the Senate"],
  [-19, "The poet Virgil dies, leaving the Aeneid unfinished"],
  [-4, "Herod the Great dies (approximately)"],

  // ---- Rome and the early Middle Ages (AD 1–999) ----
  [8, "Augustus exiles the poet Ovid to the Black Sea"],
  [9, "Three Roman legions are destroyed in the Teutoburg Forest"],
  [14, "Emperor Augustus dies"],
  [17, "The poet Ovid dies in exile (approximately)"],
  [30, "Jesus of Nazareth is crucified in Jerusalem (approximately)"],
  [37, "Emperor Tiberius dies and Caligula succeeds him"],
  [41, "Caligula is assassinated by his Praetorian Guard"],
  [43, "Emperor Claudius launches the Roman conquest of Britain"],
  [51, "Caratacus is betrayed and handed over to the Romans"],
  [60, "Boudica's Iceni revolt against Roman rule (approximately)"],
  [64, "The Great Fire of Rome burns during Nero's reign"],
  [65, "Seneca is forced to take his own life by Nero"],
  [66, "The Great Jewish Revolt against Rome begins"],
  [68, "Emperor Nero dies, ending the Julio-Claudian dynasty"],
  [69, "The Year of the Four Emperors"],
  [70, "The Romans destroy the Second Temple in Jerusalem"],
  [73, "Masada falls to the Romans (approximately)"],
  [79, "Mount Vesuvius erupts and buries Pompeii"],
  [80, "The Colosseum in Rome is inaugurated"],
  [84, "Agricola defeats the Caledonians at Mons Graupius (approximately)"],
  [98, "Trajan becomes Roman Emperor"],
  [106, "Trajan completes the conquest of Dacia"],
  [113, "Trajan's Column is dedicated in Rome"],
  [117, "The Roman Empire reaches its greatest extent as Trajan dies"],
  [122, "Construction of Hadrian's Wall begins"],
  [138, "Emperor Hadrian dies"],
  [142, "Construction of the Antonine Wall in Scotland begins"],
  [161, "Marcus Aurelius becomes Roman Emperor"],
  [165, "The Antonine Plague begins to sweep the Roman Empire"],
  [180, "Marcus Aurelius dies on campaign"],
  [192, "Emperor Commodus is strangled by a wrestler"],
  [193, "The Praetorian Guard auctions off the Roman Empire"],
  [211, "Septimius Severus dies at York"],
  [212, "Caracalla grants citizenship to all free men of the empire"],
  [235, "The murder of Severus Alexander begins the Crisis of the Third Century"],
  [260, "Emperor Valerian is captured by the Persian king Shapur I"],
  [272, "Aurelian defeats Queen Zenobia of Palmyra"],
  [284, "Diocletian becomes Roman Emperor"],
  [293, "Diocletian establishes the Tetrarchy"],
  [303, "Diocletian launches the Great Persecution of Christians"],
  [306, "Constantine is proclaimed emperor by his troops at York"],
  [312, "Constantine wins the Battle of the Milvian Bridge"],
  [313, "The Edict of Milan grants tolerance to Christians"],
  [325, "The First Council of Nicaea is convened"],
  [330, "Constantinople is dedicated as the new capital of the Roman Empire"],
  [337, "Constantine the Great dies"],
  [354, "Augustine of Hippo is born"],
  [363, "Emperor Julian the Apostate is killed fighting the Persians"],
  [367, "The Great Conspiracy: barbarians attack Roman Britain from all sides"],
  [378, "The Goths destroy a Roman army at Adrianople"],
  [380, "The Edict of Thessalonica makes Christianity the state religion"],
  [395, "The Roman Empire is permanently divided into East and West"],
  [406, "Vandals, Alans and Suebi cross the frozen Rhine (traditional)"],
  [410, "Alaric and the Visigoths sack Rome"],
  [430, "Augustine of Hippo dies as the Vandals besiege his city"],
  [432, "St Patrick begins his mission to Ireland (traditional)"],
  [439, "The Vandals capture Carthage"],
  [449, "Hengist and Horsa land in Kent (traditional)"],
  [451, "Attila the Hun is checked at the Battle of the Catalaunian Plains"],
  [452, "Attila invades Italy and meets Pope Leo I"],
  [453, "Attila the Hun dies on his wedding night"],
  [455, "The Vandals sack Rome"],
  [476, "Romulus Augustulus, last Western Roman Emperor, is deposed"],
  [481, "Clovis becomes king of the Franks"],
  [496, "Clovis, King of the Franks, is baptised (traditional)"],
  [527, "Justinian becomes Byzantine Emperor"],
  [529, "St Benedict founds the monastery at Monte Cassino (traditional)"],
  [532, "The Nika riots nearly topple Justinian in Constantinople"],
  [533, "Belisarius reconquers North Africa from the Vandals"],
  [537, "The Hagia Sophia in Constantinople is completed"],
  [541, "The Plague of Justinian strikes Constantinople"],
  [563, "St Columba founds a monastery on Iona"],
  [565, "Emperor Justinian dies"],
  [568, "The Lombards invade Italy"],
  [570, "Muhammad is born in Mecca (approximately)"],
  [590, "Gregory the Great becomes Pope"],
  [597, "Augustine arrives in Kent on a mission to convert the English"],
  [610, "Heraclius becomes Byzantine Emperor"],
  [616, "Æthelberht of Kent, first Christian English king, dies"],
  [622, "Muhammad makes the Hijra from Mecca to Medina"],
  [624, "King Rædwald, probably buried at Sutton Hoo, dies (approximately)"],
  [627, "Heraclius defeats the Persians at Nineveh"],
  [632, "Muhammad dies in Medina"],
  [636, "Arab armies defeat the Byzantines at the Battle of Yarmouk"],
  [637, "Jerusalem surrenders to the Caliph Umar (approximately)"],
  [642, "Penda of Mercia kills King Oswald at Maserfield"],
  [651, "The last Sasanian king of Persia, Yazdegerd III, is killed"],
  [664, "The Synod of Whitby"],
  [673, "The Venerable Bede is born (approximately)"],
  [680, "Husayn ibn Ali is killed at the Battle of Karbala"],
  [685, "The Picts defeat the Northumbrians at Nechtansmere"],
  [691, "The Dome of the Rock is completed in Jerusalem (approximately)"],
  [711, "The Umayyads invade Visigothic Spain"],
  [717, "The Arab siege of Constantinople begins"],
  [722, "Pelayo wins the Battle of Covadonga, beginning the Reconquista (traditional)"],
  [732, "Charles Martel halts the Umayyad advance at the Battle of Tours"],
  [735, "The Venerable Bede dies at Jarrow"],
  [742, "Charlemagne is born (approximately)"],
  [750, "The Abbasids overthrow the Umayyad Caliphate"],
  [751, "Pepin the Short becomes King of the Franks"],
  [756, "Abd al-Rahman I founds the Emirate of Córdoba"],
  [762, "The Abbasids found Baghdad"],
  [768, "Charlemagne becomes King of the Franks"],
  [778, "Roland is killed at the Battle of Roncevaux Pass"],
  [787, "The Second Council of Nicaea restores the veneration of icons"],
  [793, "Vikings raid the monastery at Lindisfarne"],
  [796, "Offa of Mercia dies"],
  [800, "Charlemagne is crowned Emperor by Pope Leo III"],
  [814, "Charlemagne dies at Aachen"],
  [843, "Kenneth MacAlpin becomes King of the Picts and Scots (traditional)"],
  [843, "The Treaty of Verdun divides Charlemagne's empire"],
  [845, "Vikings sack Paris"],
  [849, "Alfred the Great is born at Wantage"],
  [862, "Rurik establishes Viking rule at Novgorod (traditional)"],
  [865, "The Great Heathen Army lands in East Anglia"],
  [866, "The Vikings capture York"],
  [869, "King Edmund of East Anglia is killed by the Danes"],
  [871, "Alfred becomes King of Wessex"],
  [878, "Alfred the Great defeats the Danes at the Battle of Edington"],
  [885, "The Vikings besiege Paris"],
  [899, "Alfred the Great dies"],
  [911, "Rollo is granted the lands that become Normandy"],
  [925, "Æthelstan becomes King of the Anglo-Saxons"],
  [937, "Æthelstan defeats a Scots and Viking alliance at Brunanburh"],
  [954, "Eric Bloodaxe, last Viking king of York, is killed"],
  [955, "Otto I defeats the Magyars at the Lechfeld"],
  [962, "Otto I is crowned Holy Roman Emperor"],
  [973, "Edgar is crowned King of England at Bath"],
  [978, "King Edward the Martyr is murdered at Corfe"],
  [987, "Hugh Capet becomes King of France"],
  [988, "Vladimir of Kiev converts to Christianity"],
  [991, "The English are defeated by Vikings at the Battle of Maldon"],

  // ---- Medieval (1000–1499) ----
  [1000, "Leif Erikson reaches North America (approximately)"],
  [1002, "Æthelred orders the St Brice's Day massacre of Danes in England"],
  [1013, "Sweyn Forkbeard conquers England"],
  [1014, "Basil II, the Bulgar-Slayer, blinds thousands of Bulgarian prisoners"],
  [1014, "Brian Boru defeats the Vikings at Clontarf and is killed"],
  [1016, "Cnut becomes King of all England"],
  [1016, "Edmund Ironside is defeated by Cnut at Assandun"],
  [1018, "The Scots win the Battle of Carham, securing Lothian (approximately)"],
  [1028, "William the Conqueror is born (approximately)"],
  [1035, "Cnut the Great dies at Shaftesbury"],
  [1040, "Macbeth kills King Duncan I and takes the Scottish throne"],
  [1042, "Edward the Confessor becomes King of England"],
  [1054, "Chinese astronomers record the supernova that created the Crab Nebula"],
  [1054, "The Great Schism splits the Eastern and Western churches"],
  [1057, "Macbeth, King of Scots, is killed in battle by Malcolm"],
  [1061, "The Normans begin their conquest of Sicily"],
  [1065, "Westminster Abbey is consecrated under Edward the Confessor"],
  [1066, "Edward the Confessor dies"],
  [1066, "Harold Godwinson defeats Harald Hardrada at Stamford Bridge"],
  [1066, "William of Normandy defeats Harold II at the Battle of Hastings"],
  [1069, "William the Conqueror begins the Harrying of the North"],
  [1071, "Hereward the Wake makes his last stand at Ely"],
  [1071, "The Seljuks defeat the Byzantines at Manzikert"],
  [1077, "Emperor Henry IV does penance before the Pope at Canossa"],
  [1078, "Construction of the White Tower of London begins (approximately)"],
  [1085, "Alfonso VI of Castile captures Toledo"],
  [1086, "The Domesday survey of England is completed"],
  [1087, "William the Conqueror dies at Rouen"],
  [1093, "Construction of Durham Cathedral begins"],
  [1095, "Pope Urban II calls for the First Crusade at Clermont"],
  [1097, "Crusaders capture Nicaea"],
  [1098, "Crusaders capture Antioch"],
  [1099, "Crusaders capture Jerusalem"],
  [1099, "El Cid dies in Valencia"],
  [1100, "William II is killed by an arrow in the New Forest"],
  [1106, "Henry I defeats his brother Robert at Tinchebrai"],
  [1120, "The White Ship sinks, drowning Henry I's heir"],
  [1122, "Eleanor of Aquitaine is born (approximately)"],
  [1122, "The Concordat of Worms settles the Investiture Controversy"],
  [1133, "Henry II of England is born"],
  [1135, "Henry I dies, allegedly from a surfeit of lampreys"],
  [1138, "The English defeat the Scots at the Battle of the Standard"],
  [1139, "Afonso Henriques proclaims himself King of Portugal"],
  [1141, "Stephen is captured at the Battle of Lincoln"],
  [1142, "Empress Matilda escapes Oxford Castle across the snow"],
  [1144, "Zengi captures Edessa, prompting the Second Crusade"],
  [1147, "Crusaders help capture Lisbon from the Moors"],
  [1152, "Eleanor of Aquitaine marries Henry of Anjou"],
  [1153, "The Treaty of Wallingford ends the Anarchy"],
  [1154, "Henry II becomes King of England"],
  [1154, "Nicholas Breakspear becomes the only English Pope"],
  [1157, "Richard the Lionheart is born in Oxford"],
  [1162, "Thomas Becket becomes Archbishop of Canterbury"],
  [1166, "King John is born"],
  [1169, "The Anglo-Normans land in Ireland"],
  [1170, "Thomas Becket is murdered in Canterbury Cathedral"],
  [1171, "Henry II lands in Ireland to assert his lordship"],
  [1174, "William the Lion of Scotland is captured at Alnwick"],
  [1176, "The Lombard League defeats Frederick Barbarossa at Legnano"],
  [1182, "St Francis of Assisi is born (approximately)"],
  [1187, "Saladin wins the Battle of Hattin and retakes Jerusalem"],
  [1189, "Richard the Lionheart is crowned King of England"],
  [1190, "Frederick Barbarossa drowns on his way to the Holy Land"],
  [1190, "The Jews of York are massacred at Clifford's Tower"],
  [1191, "Richard the Lionheart defeats Saladin at Arsuf"],
  [1192, "Richard the Lionheart is captured in Austria on his way home"],
  [1193, "Saladin dies in Damascus"],
  [1199, "Richard the Lionheart dies from a crossbow wound at Châlus"],
  [1204, "King John loses Normandy to Philip II of France"],
  [1204, "The Fourth Crusade sacks Constantinople"],
  [1206, "Temüjin is proclaimed Genghis Khan"],
  [1208, "Pope Innocent III places England under interdict"],
  [1209, "The Albigensian Crusade begins; Béziers is massacred"],
  [1212, "Christian kingdoms defeat the Almohads at Las Navas de Tolosa"],
  [1214, "Philip II of France wins the Battle of Bouvines"],
  [1215, "King John seals Magna Carta at Runnymede"],
  [1216, "King John loses his baggage train in the Wash and dies"],
  [1217, "The rebel barons and French are beaten at the Battle of Lincoln"],
  [1219, "The Mongols invade the Khwarazmian Empire"],
  [1220, "Construction of Salisbury Cathedral begins"],
  [1223, "Pope Honorius III approves the rule of St Francis"],
  [1226, "St Francis of Assisi dies"],
  [1227, "Genghis Khan dies"],
  [1236, "Castile captures Córdoba from the Moors"],
  [1239, "Edward I is born"],
  [1240, "The Mongols sack Kiev"],
  [1241, "The Mongols defeat the Poles and Germans at Legnica"],
  [1242, "Alexander Nevsky defeats the Teutonic Knights on the ice of Lake Peipus"],
  [1248, "Seville falls to Ferdinand III of Castile"],
  [1250, "Louis IX is captured in Egypt on crusade"],
  [1254, "Marco Polo is born in Venice"],
  [1258, "The Mongols sack Baghdad"],
  [1258, "The Provisions of Oxford curb the power of Henry III"],
  [1260, "The Mamluks defeat the Mongols at Ain Jalut"],
  [1261, "The Byzantines recapture Constantinople"],
  [1264, "Simon de Montfort captures Henry III at the Battle of Lewes"],
  [1265, "Dante Alighieri is born in Florence (approximately)"],
  [1265, "Simon de Montfort is killed at the Battle of Evesham"],
  [1265, "Simon de Montfort summons a parliament with representatives of the towns"],
  [1266, "The Treaty of Perth cedes the Hebrides to Scotland"],
  [1270, "Louis IX dies on crusade at Tunis"],
  [1272, "Edward I becomes King of England"],
  [1274, "Thomas Aquinas dies"],
  [1277, "Edward I launches his first campaign against Llywelyn in Wales"],
  [1282, "Llywelyn ap Gruffudd, last native Prince of Wales, is killed"],
  [1282, "The Sicilian Vespers uprising against the French"],
  [1283, "Construction of Conwy and Caernarfon castles begins"],
  [1286, "Alexander III of Scotland falls from his horse and dies"],
  [1290, "Edward I expels the Jews from England"],
  [1290, "Margaret, Maid of Norway, dies on her way to Scotland"],
  [1291, "Acre, the last crusader stronghold, falls"],
  [1291, "The Swiss cantons form their Everlasting League"],
  [1292, "John Balliol is chosen as King of Scots"],
  [1295, "Marco Polo returns to Venice from the court of Kublai Khan"],
  [1296, "Edward I sacks Berwick and takes the Stone of Scone"],
  [1297, "William Wallace wins the Battle of Stirling Bridge"],
  [1298, "Edward I defeats William Wallace at Falkirk"],
  [1302, "Flemish militia defeat French knights at the Battle of the Golden Spurs"],
  [1304, "Petrarch is born"],
  [1305, "William Wallace is executed in London"],
  [1306, "Robert the Bruce is crowned King of Scots"],
  [1307, "Edward I, 'Hammer of the Scots', dies on campaign"],
  [1307, "Philip IV of France arrests the Knights Templar"],
  [1309, "The Papacy moves to Avignon"],
  [1312, "Edward III is born"],
  [1312, "Piers Gaveston is executed by rebel barons"],
  [1314, "Jacques de Molay, last Grand Master of the Templars, is burned"],
  [1314, "Robert the Bruce defeats Edward II at Bannockburn"],
  [1315, "The Great Famine begins in northern Europe"],
  [1320, "The Declaration of Arbroath asserts Scottish independence"],
  [1321, "Dante Alighieri dies in Ravenna"],
  [1327, "Edward II is deposed and murdered at Berkeley Castle"],
  [1328, "The Treaty of Edinburgh–Northampton recognises Scottish independence"],
  [1330, "Edward III seizes power and arrests Roger Mortimer"],
  [1330, "Edward the Black Prince is born"],
  [1333, "The English defeat the Scots at Halidon Hill"],
  [1337, "The Hundred Years' War between England and France begins"],
  [1340, "The English destroy the French fleet at Sluys"],
  [1343, "Geoffrey Chaucer is born (approximately)"],
  [1346, "Edward III's longbowmen win the Battle of Crécy"],
  [1346, "The Scots are defeated and David II captured at Neville's Cross"],
  [1347, "Edward III captures Calais"],
  [1348, "Edward III founds the Order of the Garter"],
  [1348, "The Black Death reaches England"],
  [1349, "Flagellant movements spread across Europe during the Black Death"],
  [1351, "The Statute of Labourers attempts to freeze wages after the Black Death"],
  [1356, "The Black Prince captures the French king at Poitiers"],
  [1358, "The Jacquerie peasant revolt erupts in France"],
  [1360, "The Treaty of Brétigny pauses the Hundred Years' War"],
  [1368, "The Ming dynasty is founded in China"],
  [1374, "Petrarch dies"],
  [1376, "Edward the Black Prince dies"],
  [1376, "The Good Parliament impeaches royal officials"],
  [1377, "Edward III dies and Richard II becomes king"],
  [1378, "The Western Schism begins, with rival popes in Rome and Avignon"],
  [1380, "Dmitry Donskoy defeats the Golden Horde at Kulikovo"],
  [1381, "Wat Tyler leads the Peasants' Revolt"],
  [1382, "John Wycliffe's followers produce the first English Bible (approximately)"],
  [1384, "John Wycliffe dies"],
  [1385, "Portugal defeats Castile at Aljubarrota"],
  [1386, "Henry V is born at Monmouth (approximately)"],
  [1386, "Swiss confederates defeat the Habsburgs at Sempach"],
  [1388, "The Scots defeat the English at Otterburn"],
  [1389, "The Ottomans defeat the Serbs at the Battle of Kosovo"],
  [1396, "Ottomans rout a crusading army at Nicopolis"],
  [1399, "Richard II is deposed by Henry Bolingbroke"],
  [1400, "Geoffrey Chaucer dies"],
  [1400, "Owain Glyndŵr begins his revolt in Wales"],
  [1400, "Richard II dies in captivity at Pontefract"],
  [1402, "Tamerlane captures the Ottoman Sultan at Ankara"],
  [1403, "Henry IV defeats Harry Hotspur at Shrewsbury"],
  [1405, "Tamerlane dies on campaign"],
  [1405, "Zheng He sets out on his first great voyage"],
  [1410, "Poland and Lithuania defeat the Teutonic Knights at Grunwald"],
  [1412, "Joan of Arc is born (approximately)"],
  [1413, "Henry V becomes King of England"],
  [1414, "The Council of Constance opens"],
  [1415, "Henry V defeats the French at Agincourt"],
  [1415, "Jan Hus is burned at the stake at Constance"],
  [1415, "Portugal captures Ceuta, beginning its overseas empire"],
  [1417, "The Council of Constance ends the Western Schism"],
  [1419, "Henry V captures Rouen after a long siege"],
  [1419, "The First Defenestration of Prague sparks the Hussite Wars"],
  [1420, "The Treaty of Troyes makes Henry V heir to the French throne"],
  [1422, "Henry V dies of dysentery at Vincennes"],
  [1429, "Charles VII is crowned King of France at Reims"],
  [1429, "Joan of Arc relieves the Siege of Orléans"],
  [1431, "Joan of Arc is burned at the stake in Rouen"],
  [1432, "Mehmed II, conqueror of Constantinople, is born"],
  [1434, "Cosimo de' Medici returns to rule Florence"],
  [1436, "Brunelleschi's dome of Florence Cathedral is completed"],
  [1437, "James I of Scotland is assassinated at Perth"],
  [1440, "Henry VI founds Eton College"],
  [1444, "The Ottomans defeat a crusade at Varna"],
  [1450, "Jack Cade's rebellion reaches London"],
  [1450, "The French defeat the English at Formigny"],
  [1451, "Christopher Columbus is born in Genoa (approximately)"],
  [1451, "Mehmed II becomes Ottoman Sultan"],
  [1452, "Leonardo da Vinci is born"],
  [1452, "Richard III is born at Fotheringhay"],
  [1453, "Constantinople falls to the Ottoman Turks"],
  [1453, "The French defeat the English at Castillon, ending the Hundred Years' War"],
  [1455, "The First Battle of St Albans opens the Wars of the Roses"],
  [1455, "The Gutenberg Bible is printed (approximately)"],
  [1456, "John Hunyadi breaks the Ottoman siege of Belgrade"],
  [1457, "Henry VII is born at Pembroke Castle"],
  [1460, "Richard, Duke of York, is killed at Wakefield"],
  [1461, "Edward IV wins the Battle of Towton"],
  [1462, "Vlad the Impaler's night attack on Mehmed II's camp"],
  [1464, "Edward IV secretly marries Elizabeth Woodville"],
  [1466, "Erasmus is born in Rotterdam (approximately)"],
  [1469, "Ferdinand of Aragon marries Isabella of Castile"],
  [1469, "Lorenzo de' Medici becomes ruler of Florence"],
  [1469, "Niccolò Machiavelli is born in Florence"],
  [1470, "Warwick the Kingmaker restores Henry VI to the throne"],
  [1471, "Edward IV wins the Battle of Tewkesbury"],
  [1471, "Henry VI dies in the Tower of London"],
  [1471, "Warwick the Kingmaker is killed at the Battle of Barnet"],
  [1472, "Orkney and Shetland are annexed to Scotland"],
  [1473, "Nicolaus Copernicus is born"],
  [1475, "Michelangelo is born"],
  [1476, "William Caxton sets up the first printing press in England"],
  [1477, "Charles the Bold of Burgundy is killed at Nancy"],
  [1478, "George, Duke of Clarence, is executed in the Tower"],
  [1478, "The Pazzi Conspiracy against the Medici in Florence"],
  [1478, "The Spanish Inquisition is established"],
  [1478, "Thomas More is born"],
  [1480, "Ivan III ends Mongol overlordship at the Great Stand on the Ugra"],
  [1483, "Edward IV dies; the Princes in the Tower disappear"],
  [1483, "Martin Luther is born"],
  [1483, "Raphael is born in Urbino"],
  [1483, "Richard III is crowned King of England"],
  [1485, "Henry Tudor defeats Richard III at Bosworth Field"],
  [1485, "Thomas Cromwell is born (approximately)"],
  [1487, "Henry VII defeats Lambert Simnel's rebels at Stoke Field"],
  [1488, "Bartolomeu Dias rounds the Cape of Good Hope"],
  [1488, "James III of Scotland is killed after Sauchieburn"],
  [1491, "Henry VIII is born"],
  [1492, "Columbus makes landfall in the Americas"],
  [1492, "Granada, the last Muslim kingdom in Spain, falls"],
  [1492, "Lorenzo de' Medici dies"],
  [1492, "Spain expels its Jews by the Alhambra Decree"],
  [1494, "Charles VIII of France invades Italy"],
  [1494, "The Treaty of Tordesillas divides the New World between Spain and Portugal"],
  [1495, "Leonardo da Vinci begins The Last Supper (approximately)"],
  [1497, "Cornish rebels are crushed at Blackheath"],
  [1497, "Hans Holbein the Younger is born (approximately)"],
  [1497, "John Cabot reaches Newfoundland"],
  [1498, "Savonarola is burned in Florence"],
  [1498, "Vasco da Gama reaches India by sea"],
  [1499, "Perkin Warbeck is hanged at Tyburn"],

  // ---- Renaissance, Reformation and the 1600s ----
  [1500, "Pedro Álvares Cabral reaches Brazil"],
  [1501, "Michelangelo begins carving his David"],
  [1502, "Arthur, Prince of Wales, dies at Ludlow"],
  [1503, "James IV of Scotland marries Margaret Tudor"],
  [1503, "Leonardo begins painting the Mona Lisa (approximately)"],
  [1506, "Christopher Columbus dies"],
  [1506, "Construction of the new St Peter's Basilica begins"],
  [1507, "The name 'America' first appears on the Waldseemüller map"],
  [1509, "Henry VIII becomes King and marries Catherine of Aragon"],
  [1509, "John Calvin is born"],
  [1509, "The Portuguese defeat an Ottoman-Mamluk fleet at Diu"],
  [1510, "Afonso de Albuquerque captures Goa for Portugal"],
  [1511, "The Portuguese capture Malacca"],
  [1512, "Michelangelo completes the Sistine Chapel ceiling"],
  [1513, "Balboa becomes the first European to see the Pacific from the Americas"],
  [1513, "James IV of Scotland is killed at the Battle of Flodden"],
  [1513, "Machiavelli writes The Prince"],
  [1515, "Francis I of France wins the Battle of Marignano"],
  [1515, "Thomas Wolsey becomes Lord Chancellor"],
  [1516, "Erasmus publishes his Greek New Testament"],
  [1516, "Mary I is born at Greenwich"],
  [1516, "The Ottomans defeat the Mamluks at Marj Dabiq"],
  [1516, "Thomas More publishes Utopia"],
  [1517, "Martin Luther publishes his Ninety-five Theses"],
  [1517, "The Ottomans conquer Egypt"],
  [1519, "Charles V is elected Holy Roman Emperor"],
  [1519, "Hernán Cortés lands in Mexico"],
  [1519, "Leonardo da Vinci dies in France"],
  [1520, "Henry VIII meets Francis I at the Field of the Cloth of Gold"],
  [1520, "Raphael dies in Rome"],
  [1520, "Suleiman the Magnificent becomes Ottoman Sultan"],
  [1521, "Cortés captures Tenochtitlan"],
  [1521, "Luther refuses to recant at the Diet of Worms"],
  [1521, "Magellan is killed in the Philippines"],
  [1521, "The Pope names Henry VIII 'Defender of the Faith'"],
  [1522, "Magellan's surviving crew complete the first circumnavigation"],
  [1522, "The Knights of St John surrender Rhodes to the Ottomans"],
  [1524, "The German Peasants' War breaks out"],
  [1525, "Charles V's army captures Francis I at the Battle of Pavia"],
  [1526, "Babur founds the Mughal Empire at the First Battle of Panipat"],
  [1526, "The Ottomans crush Hungary at the Battle of Mohács"],
  [1526, "William Tyndale's English New Testament is printed"],
  [1527, "Imperial troops sack Rome"],
  [1527, "Machiavelli dies"],
  [1529, "Cardinal Wolsey falls from power"],
  [1529, "The Ottomans besiege Vienna for the first time"],
  [1530, "The Augsburg Confession is presented"],
  [1532, "Pizarro captures the Inca emperor Atahualpa"],
  [1533, "Atahualpa is executed by the Spanish"],
  [1533, "Elizabeth I is born at Greenwich"],
  [1533, "Henry VIII marries Anne Boleyn"],
  [1534, "Jacques Cartier explores the Gulf of St Lawrence"],
  [1534, "The Act of Supremacy makes Henry VIII head of the Church of England"],
  [1535, "Sir Thomas More is executed"],
  [1535, "The Anabaptist Kingdom of Münster falls"],
  [1536, "Anne Boleyn is executed at the Tower of London"],
  [1536, "Calvin publishes his Institutes of the Christian Religion"],
  [1536, "Catherine of Aragon dies"],
  [1536, "Erasmus dies in Basel"],
  [1536, "The Pilgrimage of Grace rises in the north of England"],
  [1536, "The dissolution of the smaller monasteries begins in England"],
  [1537, "Edward VI is born at Hampton Court"],
  [1537, "Jane Seymour dies after giving birth to the future Edward VI"],
  [1538, "The Ottomans defeat a Holy League fleet at Preveza"],
  [1540, "Henry VIII marries and divorces Anne of Cleves"],
  [1540, "The Pope formally approves the Jesuit order"],
  [1540, "Thomas Cromwell is executed"],
  [1541, "Henry VIII is proclaimed King of Ireland"],
  [1542, "Catherine Howard is executed"],
  [1542, "Mary, Queen of Scots, is born at Linlithgow"],
  [1542, "The Scots are routed at Solway Moss; Mary becomes Queen of Scots as a baby"],
  [1543, "Copernicus publishes his theory of a sun-centred universe"],
  [1543, "Hans Holbein the Younger dies in London"],
  [1543, "Nicolaus Copernicus dies"],
  [1543, "Vesalius publishes his great work of human anatomy"],
  [1544, "Henry VIII captures Boulogne"],
  [1545, "The Council of Trent opens"],
  [1545, "The Mary Rose sinks off Portsmouth"],
  [1546, "Martin Luther dies"],
  [1547, "Henry VIII dies"],
  [1547, "Ivan IV is crowned the first Tsar of Russia"],
  [1547, "Miguel de Cervantes is born"],
  [1547, "The Scots are defeated at the Battle of Pinkie"],
  [1549, "Kett's Rebellion in Norfolk is crushed"],
  [1549, "The Prayer Book Rebellion erupts in Devon and Cornwall"],
  [1549, "The first Book of Common Prayer is introduced"],
  [1552, "Ivan the Terrible conquers Kazan"],
  [1553, "Edward VI dies aged fifteen"],
  [1554, "Lady Jane Grey is executed"],
  [1554, "Wyatt's Rebellion against Mary I's Spanish marriage"],
  [1555, "Bishops Latimer and Ridley are burned at Oxford"],
  [1555, "The Peace of Augsburg"],
  [1556, "Charles V abdicates"],
  [1556, "Thomas Cranmer is burned at the stake"],
  [1557, "Spain defeats France at the Battle of St Quentin"],
  [1558, "Elizabeth I becomes Queen"],
  [1558, "England loses Calais, its last possession in France"],
  [1559, "Elizabeth I is crowned"],
  [1559, "The Peace of Cateau-Cambrésis"],
  [1560, "The Scottish Parliament adopts the Protestant faith"],
  [1561, "Francis Bacon is born"],
  [1562, "The French Wars of Religion begin"],
  [1563, "The Thirty-Nine Articles are established"],
  [1564, "Galileo Galilei is born in Pisa"],
  [1564, "John Calvin dies in Geneva"],
  [1564, "Michelangelo dies"],
  [1564, "William Shakespeare is born in Stratford-upon-Avon"],
  [1565, "The Knights of St John withstand the Great Siege of Malta"],
  [1566, "James VI and I is born in Edinburgh Castle"],
  [1566, "Suleiman the Magnificent dies"],
  [1566, "The Dutch Revolt begins with the iconoclastic fury"],
  [1567, "Lord Darnley is murdered at Kirk o' Field"],
  [1567, "Mary, Queen of Scots, is forced to abdicate"],
  [1568, "Mary, Queen of Scots, flees to England after defeat at Langside"],
  [1569, "Mercator publishes his world map projection"],
  [1569, "The Rising of the North against Elizabeth I"],
  [1570, "Pope Pius V excommunicates Elizabeth I"],
  [1571, "Johannes Kepler is born"],
  [1571, "The Holy League defeats the Ottoman fleet at Lepanto"],
  [1571, "The Ottomans capture Cyprus"],
  [1571, "The Ridolfi plot against Elizabeth I is uncovered"],
  [1572, "The St Bartholomew's Day Massacre of Huguenots in Paris"],
  [1576, "Spanish troops sack Antwerp in the Spanish Fury"],
  [1577, "Francis Drake sets out on his circumnavigation"],
  [1577, "Peter Paul Rubens is born"],
  [1580, "Drake returns from circumnavigating the globe"],
  [1580, "Philip II of Spain seizes the Portuguese crown"],
  [1581, "The Dutch Act of Abjuration renounces Philip II"],
  [1582, "The Gregorian calendar is introduced"],
  [1584, "William the Silent is assassinated in Delft"],
  [1585, "The Roanoke colony is founded"],
  [1586, "Sir Philip Sidney is mortally wounded at Zutphen"],
  [1586, "The Babington Plot is uncovered"],
  [1587, "Drake 'singes the King of Spain's beard' at Cádiz"],
  [1587, "Mary, Queen of Scots, is executed at Fotheringhay"],
  [1588, "The Spanish Armada is defeated"],
  [1589, "Henry III of France is assassinated"],
  [1590, "Henry IV of France wins the Battle of Ivry"],
  [1592, "Toyotomi Hideyoshi invades Korea"],
  [1593, "Christopher Marlowe is killed in a Deptford tavern"],
  [1593, "Henry IV of France converts: 'Paris is well worth a Mass'"],
  [1596, "René Descartes is born"],
  [1596, "Sir Francis Drake dies off Panama"],
  [1596, "The English sack Cádiz"],
  [1598, "Philip II of Spain dies"],
  [1598, "The Edict of Nantes grants rights to French Protestants"],
  [1598, "The Irish win the Battle of the Yellow Ford"],
  [1599, "Oliver Cromwell is born in Huntingdon"],
  [1599, "The Globe Theatre opens"],
  [1600, "Charles I is born at Dunfermline"],
  [1600, "Giordano Bruno is burned in Rome"],
  [1600, "The East India Company is granted its royal charter"],
  [1600, "Tokugawa Ieyasu wins the Battle of Sekigahara"],
  [1601, "The Earl of Essex is executed after his failed rebellion"],
  [1601, "The English defeat the Irish and Spanish at Kinsale"],
  [1602, "The Dutch East India Company is founded"],
  [1603, "Elizabeth I dies and James VI of Scotland takes the English throne"],
  [1603, "James I is crowned King of England"],
  [1603, "Tokugawa Ieyasu becomes shogun of Japan"],
  [1604, "The Hampton Court Conference commissions a new Bible"],
  [1605, "The Gunpowder Plot is foiled"],
  [1606, "Guy Fawkes is executed"],
  [1606, "Macbeth is first performed (approximately)"],
  [1606, "Rembrandt is born in Leiden"],
  [1607, "Jamestown is founded in Virginia"],
  [1607, "The Flight of the Earls from Ireland"],
  [1608, "John Milton is born in London"],
  [1608, "Samuel de Champlain founds Quebec"],
  [1609, "Galileo first turns a telescope to the heavens"],
  [1609, "The Plantation of Ulster begins"],
  [1610, "Henry Hudson reaches Hudson Bay"],
  [1610, "Henry IV of France is assassinated by Ravaillac"],
  [1611, "The King James Bible is published"],
  [1612, "Henry, Prince of Wales, dies of typhoid"],
  [1613, "Michael Romanov is elected Tsar, founding the Romanov dynasty"],
  [1613, "The Globe Theatre burns down during Henry VIII"],
  [1616, "Miguel de Cervantes dies"],
  [1616, "Pocahontas visits England"],
  [1616, "William Shakespeare dies"],
  [1618, "Sir Walter Raleigh is executed"],
  [1618, "The Defenestration of Prague sparks the Thirty Years' War"],
  [1619, "The first enslaved Africans arrive in English Virginia"],
  [1620, "The Catholic League wins the Battle of White Mountain"],
  [1620, "The Mayflower sails for the New World"],
  [1621, "The Plymouth colonists hold a harvest feast"],
  [1623, "Shakespeare's First Folio is published"],
  [1624, "Cardinal Richelieu becomes chief minister of France"],
  [1625, "Charles I becomes King of England"],
  [1626, "Francis Bacon dies after an experiment stuffing a chicken with snow"],
  [1626, "The Dutch buy Manhattan"],
  [1628, "La Rochelle surrenders to Richelieu"],
  [1628, "Parliament presents the Petition of Right"],
  [1628, "The Duke of Buckingham is assassinated in Portsmouth"],
  [1628, "The Swedish warship Vasa sinks on her maiden voyage"],
  [1628, "William Harvey publishes his account of the circulation of the blood"],
  [1629, "Charles I begins his Personal Rule without Parliament"],
  [1630, "Charles II is born"],
  [1630, "Gustavus Adolphus lands in Germany"],
  [1630, "Johannes Kepler dies"],
  [1631, "Gustavus Adolphus wins the Battle of Breitenfeld"],
  [1631, "Imperial troops sack Magdeburg"],
  [1632, "Christopher Wren is born"],
  [1632, "Galileo publishes his Dialogue on the Two Chief World Systems"],
  [1632, "Gustavus Adolphus of Sweden is killed at the Battle of Lützen"],
  [1632, "John Locke is born"],
  [1633, "Galileo is tried by the Inquisition"],
  [1634, "Wallenstein is assassinated"],
  [1637, "Descartes publishes 'I think, therefore I am'"],
  [1637, "Jenny Geddes hurls her stool in St Giles' over the new Prayer Book"],
  [1637, "Tulip mania collapses in the Netherlands"],
  [1638, "Louis XIV is born"],
  [1638, "The Scottish National Covenant is signed"],
  [1639, "The First Bishops' War between Charles I and the Scots"],
  [1640, "Charles I summons the Long Parliament"],
  [1640, "Peter Paul Rubens dies"],
  [1640, "Portugal regains independence from Spain"],
  [1641, "The Earl of Strafford is executed"],
  [1641, "The Irish Rebellion breaks out in Ulster"],
  [1642, "Abel Tasman reaches Tasmania and New Zealand"],
  [1642, "Charles I tries to arrest five MPs in the Commons"],
  [1642, "Galileo Galilei dies under house arrest"],
  [1642, "Isaac Newton is born in Lincolnshire (by the calendar then used in England)"],
  [1643, "France defeats Spain at the Battle of Rocroi"],
  [1643, "Louis XIV becomes King of France aged four"],
  [1644, "Parliament wins the Battle of Marston Moor"],
  [1644, "The Ming dynasty falls and the Qing take Beijing"],
  [1645, "Archbishop Laud is executed"],
  [1645, "Cromwell's New Model Army wins the Battle of Naseby"],
  [1645, "The New Model Army is formed"],
  [1647, "The Putney Debates on the future constitution"],
  [1648, "Cromwell defeats the Scots and Royalists at Preston"],
  [1648, "Pride's Purge of Parliament"],
  [1648, "The Fronde rebellion begins in France"],
  [1648, "The Peace of Westphalia ends the Thirty Years' War"],
  [1649, "Cromwell storms Drogheda"],
  [1649, "England is declared a Commonwealth"],
  [1649, "King Charles I is executed in Whitehall"],
  [1650, "Cromwell defeats the Scots at Dunbar"],
  [1650, "John Churchill, future Duke of Marlborough, is born"],
  [1650, "René Descartes dies in Stockholm"],
  [1651, "Charles II hides in the Royal Oak at Boscobel"],
  [1651, "Cromwell defeats Charles II at Worcester"],
  [1651, "Hobbes publishes Leviathan"],
  [1652, "The Dutch found a colony at the Cape of Good Hope"],
  [1652, "The First Anglo-Dutch War begins"],
  [1653, "Cromwell becomes Lord Protector"],
  [1655, "England captures Jamaica from Spain"],
  [1656, "Cromwell readmits the Jews to England"],
  [1658, "Anglo-French forces win the Battle of the Dunes"],
  [1658, "Oliver Cromwell dies"],
  [1659, "The Peace of the Pyrenees between France and Spain"],
  [1660, "Samuel Pepys begins his diary"],
  [1660, "The monarchy is restored under Charles II"],
  [1661, "Charles II is crowned"],
  [1661, "Cromwell's body is exhumed and posthumously executed"],
  [1661, "Louis XIV begins his personal rule"],
  [1662, "Charles II marries Catherine of Braganza, gaining Bombay"],
  [1662, "The Act of Uniformity forces out dissenting clergy"],
  [1664, "The English capture New Amsterdam and rename it New York"],
  [1665, "Newton develops calculus while sheltering from the plague (approximately)"],
  [1665, "The Great Plague ravages London"],
  [1666, "The Great Fire of London"],
  [1666, "The village of Eyam isolates itself to contain the plague"],
  [1667, "Milton publishes Paradise Lost"],
  [1667, "The Dutch raid the Medway and tow away the Royal Charles"],
  [1669, "Rembrandt dies in Amsterdam"],
  [1670, "The Hudson's Bay Company is chartered"],
  [1670, "The secret Treaty of Dover between Charles II and Louis XIV"],
  [1671, "Colonel Blood tries to steal the Crown Jewels"],
  [1672, "Peter the Great is born"],
  [1673, "The Test Act bars Catholics from public office"],
  [1674, "John Milton dies"],
  [1675, "Construction of the new St Paul's Cathedral begins"],
  [1675, "The Royal Observatory at Greenwich is founded"],
  [1678, "Bunyan publishes The Pilgrim's Progress"],
  [1678, "Titus Oates invents the Popish Plot"],
  [1679, "The Covenanters are defeated at Bothwell Bridge"],
  [1679, "The Habeas Corpus Act is passed"],
  [1681, "William Penn receives the charter for Pennsylvania"],
  [1682, "La Salle claims Louisiana for France"],
  [1682, "Louis XIV moves his court to Versailles"],
  [1682, "Peter the Great becomes co-Tsar of Russia"],
  [1683, "The Ottoman Siege of Vienna is broken"],
  [1683, "The Rye House Plot to kill Charles II"],
  [1685, "Charles II dies and converts to Catholicism on his deathbed"],
  [1685, "George Frideric Handel is born"],
  [1685, "Johann Sebastian Bach is born"],
  [1685, "Judge Jeffreys holds the Bloody Assizes"],
  [1685, "Louis XIV revokes the Edict of Nantes"],
  [1685, "Monmouth's Rebellion ends at the Battle of Sedgemoor"],
  [1686, "The Habsburgs retake Buda from the Ottomans"],
  [1687, "Isaac Newton publishes his Principia"],
  [1687, "The Venetians shell the Parthenon, blowing up an Ottoman powder store"],
  [1688, "The Glorious Revolution: William of Orange lands at Torbay"],
  [1689, "The Bill of Rights is passed"],
  [1689, "The Jacobites win at Killiecrankie but lose their leader"],
  [1689, "The Siege of Derry is lifted"],
  [1689, "The Treaty of Nerchinsk between Russia and China"],
  [1690, "The French defeat the Anglo-Dutch fleet at Beachy Head"],
  [1690, "William III defeats James II at the Battle of the Boyne"],
  [1691, "The Treaty of Limerick ends the Williamite War in Ireland"],
  [1692, "An earthquake destroys Port Royal, Jamaica"],
  [1692, "The Massacre of Glencoe"],
  [1692, "The Salem witch trials"],
  [1694, "Queen Mary II dies of smallpox"],
  [1694, "The Bank of England is founded"],
  [1695, "The Bank of Scotland is founded"],
  [1697, "Peter the Great's Grand Embassy sets out to western Europe"],
  [1697, "Prince Eugene crushes the Ottomans at Zenta"],
  [1697, "The Treaty of Ryswick ends the Nine Years' War"],
  [1698, "The Darien scheme sets sail from Scotland"],
  [1698, "The Palace of Whitehall burns down"],
  [1699, "The Treaty of Karlowitz forces the Ottomans to cede Hungary"],

  // ---- The 1700s ----
  [1700, "Charles XII of Sweden routs the Russians at Narva"],
  [1701, "Jethro Tull invents his seed drill (approximately)"],
  [1701, "The Act of Settlement secures a Protestant succession"],
  [1701, "The War of the Spanish Succession begins"],
  [1702, "Queen Anne becomes Queen"],
  [1702, "William III dies after his horse stumbles on a molehill"],
  [1703, "Peter the Great founds St Petersburg"],
  [1703, "Samuel Pepys dies"],
  [1704, "John Locke dies"],
  [1704, "Marlborough wins the Battle of Blenheim"],
  [1704, "The English capture Gibraltar"],
  [1706, "Benjamin Franklin is born in Boston"],
  [1706, "Marlborough wins the Battle of Ramillies"],
  [1707, "The Acts of Union join England and Scotland"],
  [1708, "Marlborough wins the Battle of Oudenarde"],
  [1709, "Abraham Darby first smelts iron with coke at Coalbrookdale"],
  [1709, "Marlborough wins the bloody Battle of Malplaquet"],
  [1709, "Peter the Great defeats Charles XII of Sweden at Poltava"],
  [1709, "Samuel Johnson is born in Lichfield"],
  [1710, "The Statute of Anne, the first copyright law, takes effect"],
  [1711, "The South Sea Company is founded"],
  [1712, "Frederick the Great is born"],
  [1712, "Jean-Jacques Rousseau is born in Geneva"],
  [1712, "Thomas Newcomen's steam engine begins pumping a mine"],
  [1713, "The Treaty of Utrecht; Britain gains Gibraltar and Newfoundland"],
  [1714, "Queen Anne dies and George I arrives from Hanover"],
  [1715, "Louis XIV, the Sun King, dies"],
  [1715, "The Jacobites are defeated at Sheriffmuir and Preston"],
  [1717, "Handel's Water Music is first performed on the Thames"],
  [1717, "Maria Theresa is born"],
  [1718, "Blackbeard is killed off North Carolina"],
  [1719, "Daniel Defoe publishes Robinson Crusoe"],
  [1720, "The South Sea Bubble bursts"],
  [1721, "Lady Mary Wortley Montagu promotes smallpox inoculation in England"],
  [1721, "Robert Walpole becomes Britain's first de facto Prime Minister"],
  [1721, "The Treaty of Nystad makes Russia the dominant Baltic power"],
  [1722, "The Duke of Marlborough dies"],
  [1723, "Adam Smith is born in Kirkcaldy"],
  [1723, "Christopher Wren dies"],
  [1724, "Peter the Great founds the Russian Academy of Sciences"],
  [1725, "Peter the Great dies"],
  [1726, "Jonathan Swift publishes Gulliver's Travels"],
  [1727, "George II becomes King"],
  [1727, "Isaac Newton dies"],
  [1728, "Vitus Bering sails through the Bering Strait"],
  [1729, "Catherine the Great is born"],
  [1729, "John and Charles Wesley found the Holy Club at Oxford"],
  [1731, "Daniel Defoe dies"],
  [1732, "George Washington is born in Virginia"],
  [1733, "John Kay patents the flying shuttle"],
  [1733, "The Excise Crisis damages Walpole"],
  [1736, "James Watt is born in Greenock"],
  [1736, "The Porteous Riots break out in Edinburgh"],
  [1737, "Edward Gibbon is born"],
  [1738, "John Wesley feels his heart 'strangely warmed'"],
  [1739, "Nader Shah sacks Delhi and carries off the Peacock Throne"],
  [1739, "The War of Jenkins' Ear breaks out"],
  [1740, "Frederick the Great invades Silesia"],
  [1740, "Maria Theresa inherits the Habsburg lands"],
  [1742, "Handel's Messiah premieres in Dublin"],
  [1742, "Walpole resigns as Prime Minister"],
  [1743, "George II leads troops into battle at Dettingen, the last British king to do so"],
  [1743, "Thomas Jefferson is born"],
  [1745, "Bonnie Prince Charlie lands in Scotland"],
  [1745, "Jonathan Swift dies"],
  [1745, "The French defeat the British at Fontenoy"],
  [1745, "The Jacobites win the Battle of Prestonpans"],
  [1746, "The Jacobites are crushed at the Battle of Culloden"],
  [1747, "Lord Lovat is the last man beheaded in Britain"],
  [1748, "The Treaty of Aix-la-Chapelle ends the War of the Austrian Succession"],
  [1749, "Johann Wolfgang von Goethe is born in Frankfurt"],
  [1750, "Johann Sebastian Bach dies"],
  [1751, "Diderot publishes the first volume of the Encyclopédie"],
  [1751, "Robert Clive seizes Arcot"],
  [1752, "Benjamin Franklin flies a kite in a thunderstorm (approximately)"],
  [1752, "Britain adopts the Gregorian calendar and skips eleven days"],
  [1753, "The British Museum is founded"],
  [1754, "George Washington fights at Fort Necessity"],
  [1755, "An earthquake and tsunami devastate Lisbon"],
  [1755, "General Braddock is defeated and killed near Fort Duquesne"],
  [1755, "Marie Antoinette is born in Vienna"],
  [1756, "The Black Hole of Calcutta"],
  [1756, "The Seven Years' War begins"],
  [1756, "Wolfgang Amadeus Mozart is born in Salzburg"],
  [1757, "Admiral Byng is executed on his own quarterdeck"],
  [1757, "Clive wins the Battle of Plassey"],
  [1757, "Frederick the Great wins the Battle of Leuthen"],
  [1757, "Frederick the Great wins the Battle of Rossbach"],
  [1757, "William Blake is born in London"],
  [1758, "Horatio Nelson is born in Norfolk"],
  [1759, "British and allied infantry win the Battle of Minden"],
  [1759, "General Wolfe captures Quebec on the Plains of Abraham"],
  [1759, "Handel dies in London"],
  [1759, "Hawke destroys the French fleet at Quiberon Bay"],
  [1759, "Robert Burns is born in Alloway"],
  [1759, "The British Museum opens to the public"],
  [1759, "Voltaire publishes Candide"],
  [1759, "William Wilberforce is born in Hull"],
  [1760, "George III becomes King"],
  [1760, "Montreal surrenders to the British"],
  [1761, "The Bridgewater Canal opens"],
  [1762, "Catherine the Great seizes the Russian throne"],
  [1762, "Rousseau publishes The Social Contract"],
  [1762, "The future George IV is born"],
  [1763, "The Treaty of Paris ends the Seven Years' War"],
  [1764, "James Hargreaves invents the spinning jenny (approximately)"],
  [1765, "Parliament passes the Stamp Act"],
  [1766, "The Stamp Act is repealed"],
  [1768, "Captain Cook sets sail on HMS Endeavour"],
  [1768, "The Royal Academy of Arts is founded"],
  [1768, "The first edition of the Encyclopaedia Britannica begins publication"],
  [1769, "James Watt patents his improved steam engine"],
  [1769, "Napoleon Bonaparte is born in Corsica"],
  [1769, "Richard Arkwright patents the water frame"],
  [1769, "The Duke of Wellington is born"],
  [1770, "Captain Cook lands at Botany Bay"],
  [1770, "Lord North becomes Prime Minister"],
  [1770, "The Boston Massacre"],
  [1770, "William Wordsworth is born"],
  [1771, "Arkwright opens his mill at Cromford"],
  [1771, "Walter Scott is born in Edinburgh"],
  [1772, "The Somerset case rules on slavery in England"],
  [1772, "The first partition of Poland"],
  [1773, "Pope Clement XIV suppresses the Jesuits"],
  [1773, "The Boston Tea Party"],
  [1773, "The Pugachev Rebellion begins in Russia"],
  [1774, "Joseph Priestley isolates oxygen"],
  [1774, "Louis XVI becomes King of France"],
  [1775, "J. M. W. Turner is born"],
  [1775, "Jane Austen is born"],
  [1775, "The Battle of Bunker Hill"],
  [1775, "The first shots of the American Revolution at Lexington and Concord"],
  [1776, "Adam Smith publishes The Wealth of Nations"],
  [1776, "Gibbon publishes the first volume of The Decline and Fall of the Roman Empire"],
  [1776, "The American Declaration of Independence is adopted"],
  [1776, "Washington crosses the Delaware"],
  [1777, "Burgoyne surrenders at Saratoga"],
  [1778, "Captain Cook reaches Hawaii"],
  [1778, "France enters the American War of Independence"],
  [1778, "Rousseau dies"],
  [1778, "Voltaire dies in Paris"],
  [1779, "Captain James Cook is killed in Hawaii"],
  [1779, "The Great Siege of Gibraltar begins"],
  [1779, "The Iron Bridge is erected at Coalbrookdale"],
  [1780, "The Gordon Riots rage in London"],
  [1781, "Cornwallis surrenders to Washington at Yorktown"],
  [1781, "William Herschel discovers Uranus"],
  [1782, "Rodney defeats the French at the Battle of the Saintes"],
  [1783, "The Laki eruption in Iceland darkens European skies"],
  [1783, "The Montgolfier brothers launch the first crewed balloon flight"],
  [1783, "The Treaty of Paris recognises American independence"],
  [1783, "William Pitt the Younger becomes Prime Minister aged 24"],
  [1784, "Samuel Johnson dies"],
  [1785, "The Diamond Necklace Affair scandalises Marie Antoinette"],
  [1786, "Frederick the Great dies"],
  [1786, "Mozart's The Marriage of Figaro premieres in Vienna"],
  [1787, "The Society for Effecting the Abolition of the Slave Trade is founded"],
  [1787, "The US Constitution is signed in Philadelphia"],
  [1788, "George III's first major bout of madness triggers the Regency Crisis"],
  [1788, "Lord Byron is born"],
  [1788, "The First Fleet arrives in Australia"],
  [1788, "The trial of Warren Hastings opens"],
  [1789, "George Washington becomes the first US President"],
  [1789, "The Declaration of the Rights of Man and of the Citizen"],
  [1789, "The Estates-General meets at Versailles"],
  [1789, "The Storming of the Bastille"],
  [1789, "The Tennis Court Oath"],
  [1789, "The Women's March on Versailles"],
  [1789, "The mutiny on the Bounty"],
  [1790, "Adam Smith dies"],
  [1790, "Benjamin Franklin dies"],
  [1790, "Edmund Burke publishes Reflections on the Revolution in France"],
  [1791, "Louis XVI's flight is halted at Varennes"],
  [1791, "Mozart dies in Vienna"],
  [1791, "The Haitian Revolution begins"],
  [1791, "Thomas Paine publishes Rights of Man"],
  [1792, "Mary Wollstonecraft publishes A Vindication of the Rights of Woman"],
  [1792, "Percy Bysshe Shelley is born"],
  [1792, "The French Republic is proclaimed"],
  [1792, "The French army halts the Prussians at Valmy"],
  [1792, "The September Massacres in Paris"],
  [1793, "King Louis XVI is guillotined"],
  [1793, "Marat is murdered in his bath by Charlotte Corday"],
  [1793, "Marie Antoinette is guillotined"],
  [1793, "Napoleon distinguishes himself at the Siege of Toulon"],
  [1793, "The Louvre opens as a public museum"],
  [1793, "The Reign of Terror begins"],
  [1794, "Lavoisier is guillotined"],
  [1794, "Robespierre is guillotined"],
  [1794, "The Royal Navy wins the Glorious First of June"],
  [1795, "John Keats is born in London"],
  [1795, "Napoleon disperses a royalist mob with a 'whiff of grapeshot'"],
  [1795, "The third partition of Poland wipes it off the map"],
  [1796, "Catherine the Great dies"],
  [1796, "Edward Jenner performs the first smallpox vaccination"],
  [1796, "Napoleon begins his Italian campaign"],
  [1796, "Robert Burns dies"],
  [1797, "Mary Shelley is born"],
  [1797, "Nelson loses his arm at Santa Cruz de Tenerife"],
  [1797, "The British win the Battle of Cape St Vincent"],
  [1797, "The Republic of Venice falls to Napoleon"],
  [1797, "The Royal Navy mutinies at Spithead and the Nore"],
  [1797, "The last invasion of mainland Britain, at Fishguard"],
  [1798, "Malthus publishes his Essay on the Principle of Population"],
  [1798, "Napoleon wins the Battle of the Pyramids"],
  [1798, "Nelson destroys the French fleet at the Battle of the Nile"],
  [1798, "The Irish Rebellion; the rebels are crushed at Vinegar Hill"],
  [1798, "Wordsworth and Coleridge publish Lyrical Ballads"],
  [1799, "French soldiers discover the Rosetta Stone"],
  [1799, "George Washington dies"],
  [1799, "Napoleon seizes power in the Coup of 18 Brumaire"],
  [1799, "Tipu Sultan is killed at Seringapatam"],
  [1799, "William Pitt introduces income tax"],

  // ---- The 1800s ----
  [1800, "Alessandro Volta invents the electric battery"],
  [1800, "Napoleon defeats the Austrians at Marengo"],
  [1801, "Nelson wins the Battle of Copenhagen, ignoring the signal to withdraw"],
  [1801, "The Act of Union with Ireland creates the United Kingdom"],
  [1801, "Tsar Paul I is murdered in St Petersburg"],
  [1802, "The Peace of Amiens brings a brief pause in war with France"],
  [1803, "Robert Emmet's rising in Dublin fails"],
  [1803, "The Louisiana Purchase doubles the size of the United States"],
  [1804, "Haiti declares independence"],
  [1804, "Napoleon crowns himself Emperor of the French"],
  [1804, "Napoleon issues his Civil Code"],
  [1804, "Richard Trevithick runs the first steam railway locomotive"],
  [1805, "Napoleon crushes the Austrians and Russians at Austerlitz"],
  [1805, "Nelson is killed winning the Battle of Trafalgar"],
  [1805, "The Austrians surrender at Ulm"],
  [1806, "Britain seizes the Cape Colony from the Dutch"],
  [1806, "Isambard Kingdom Brunel is born"],
  [1806, "Napoleon defeats Prussia at Jena and Auerstedt"],
  [1806, "The Holy Roman Empire is dissolved"],
  [1806, "William Pitt the Younger dies"],
  [1807, "Pall Mall becomes the first street lit by gas"],
  [1807, "Parliament abolishes the British slave trade"],
  [1807, "The Royal Navy bombards Copenhagen and seizes the Danish fleet"],
  [1807, "The Treaties of Tilsit between Napoleon and the Tsar"],
  [1808, "The Madrid uprising against the French"],
  [1808, "The Peninsular War begins"],
  [1809, "Abraham Lincoln is born"],
  [1809, "Alfred Tennyson is born"],
  [1809, "Charles Darwin is born"],
  [1809, "Joseph Haydn dies in Vienna"],
  [1809, "Napoleon wins the Battle of Wagram"],
  [1809, "Sir John Moore is killed at Corunna"],
  [1809, "Wellesley wins the Battle of Talavera"],
  [1810, "Mexico's struggle for independence begins with the Cry of Dolores"],
  [1810, "Wellington holds the Lines of Torres Vedras"],
  [1811, "Jane Austen publishes Sense and Sensibility"],
  [1811, "Luddites begin smashing machines in Nottinghamshire"],
  [1811, "The Prince of Wales becomes Prince Regent"],
  [1811, "William Makepeace Thackeray is born in Calcutta"],
  [1812, "Charles Dickens is born"],
  [1812, "Moscow burns as Napoleon occupies it"],
  [1812, "Napoleon's Grande Armée invades Russia"],
  [1812, "Prime Minister Spencer Perceval is assassinated in the Commons"],
  [1812, "The Battle of Borodino"],
  [1812, "The United States declares war on Britain"],
  [1812, "Wellington wins the Battle of Salamanca"],
  [1813, "Jane Austen publishes Pride and Prejudice"],
  [1813, "Napoleon is defeated at the Battle of Leipzig"],
  [1813, "Richard Wagner is born"],
  [1813, "Wellington wins the Battle of Vitoria"],
  [1814, "British troops burn Washington, D.C."],
  [1814, "George Stephenson builds his first locomotive, Blücher"],
  [1814, "Napoleon abdicates and is exiled to Elba"],
  [1814, "The Congress of Vienna opens"],
  [1815, "Napoleon escapes from Elba and begins his Hundred Days"],
  [1815, "Otto von Bismarck is born"],
  [1815, "The Americans defeat the British at New Orleans"],
  [1815, "The Corn Laws are passed"],
  [1815, "The eruption of Mount Tambora"],
  [1815, "Wellington and Blücher defeat Napoleon at Waterloo"],
  [1816, "The 'Year Without a Summer'"],
  [1817, "Jane Austen dies"],
  [1818, "Emily Brontë is born"],
  [1818, "Karl Marx is born"],
  [1818, "Mary Shelley publishes Frankenstein"],
  [1819, "Cavalry charge a crowd in Manchester at the Peterloo Massacre"],
  [1819, "James Watt dies"],
  [1819, "Simón Bolívar wins the Battle of Boyacá"],
  [1819, "Stamford Raffles founds modern Singapore"],
  [1820, "George III dies"],
  [1820, "Queen Caroline's trial scandalises Britain"],
  [1820, "The Cato Street Conspiracy to murder the Cabinet"],
  [1820, "The Venus de Milo is discovered on Melos"],
  [1821, "Faraday demonstrates electromagnetic rotation"],
  [1821, "John Keats dies in Rome"],
  [1821, "Napoleon dies in exile on St Helena"],
  [1821, "The Greek War of Independence begins"],
  [1822, "Brazil declares independence from Portugal"],
  [1822, "Champollion deciphers Egyptian hieroglyphs"],
  [1822, "Shelley drowns off the Italian coast"],
  [1823, "The Monroe Doctrine is proclaimed"],
  [1824, "Beethoven's Ninth Symphony premieres"],
  [1824, "Lord Byron dies at Missolonghi"],
  [1824, "The National Gallery is founded in London"],
  [1825, "The Decembrist revolt in Russia"],
  [1825, "The Stockton and Darlington Railway opens"],
  [1827, "Beethoven dies in Vienna"],
  [1827, "The Allied fleet destroys the Ottoman-Egyptian navy at Navarino"],
  [1827, "William Blake dies"],
  [1828, "Leo Tolstoy is born"],
  [1828, "The Duke of Wellington becomes Prime Minister"],
  [1829, "Burke and Hare's murderer William Burke is hanged"],
  [1829, "Robert Peel founds the Metropolitan Police"],
  [1829, "Stephenson's Rocket wins the Rainhill Trials"],
  [1829, "The Catholic Emancipation Act is passed"],
  [1830, "Belgium revolts against Dutch rule"],
  [1830, "George IV dies"],
  [1830, "The July Revolution in France"],
  [1830, "The Liverpool and Manchester Railway opens"],
  [1830, "The Swing Riots spread through southern England"],
  [1831, "Cholera reaches Britain for the first time"],
  [1831, "Darwin sets sail on HMS Beagle"],
  [1831, "Faraday discovers electromagnetic induction"],
  [1832, "Goethe dies in Weimar"],
  [1832, "The Great Reform Act is passed"],
  [1832, "Walter Scott dies"],
  [1833, "The Slavery Abolition Act is passed in Britain"],
  [1833, "William Wilberforce dies"],
  [1834, "The New Poor Law creates the workhouse system"],
  [1834, "The Palace of Westminster burns down"],
  [1834, "The Tolpuddle Martyrs are transported"],
  [1835, "Darwin visits the Galápagos Islands"],
  [1836, "Dickens begins publishing The Pickwick Papers"],
  [1836, "The Alamo falls"],
  [1836, "The Great Trek of the Boers begins"],
  [1837, "John Constable dies"],
  [1837, "Victoria becomes Queen"],
  [1837, "William IV dies"],
  [1838, "Grace Darling rescues shipwrecked survivors"],
  [1838, "The Great Western steamship crosses the Atlantic"],
  [1838, "The People's Charter is published"],
  [1838, "Victoria is crowned"],
  [1839, "Britain's army marches into Afghanistan"],
  [1839, "Daguerre presents his photographic process"],
  [1839, "The First Opium War begins"],
  [1840, "Queen Victoria marries Prince Albert"],
  [1840, "The Penny Black, the first postage stamp, is issued"],
  [1840, "The Treaty of Waitangi is signed in New Zealand"],
  [1840, "Thomas Hardy is born"],
  [1842, "The British army is annihilated retreating from Kabul"],
  [1842, "The Mines Act bans women and children underground"],
  [1842, "The Treaty of Nanking cedes Hong Kong to Britain"],
  [1843, "Brunel launches the SS Great Britain"],
  [1843, "Dickens publishes A Christmas Carol"],
  [1843, "The Disruption splits the Church of Scotland"],
  [1843, "The Thames Tunnel opens"],
  [1844, "Samuel Morse sends the first long-distance telegraph message"],
  [1845, "The Franklin Expedition sets out for the Northwest Passage"],
  [1845, "The Great Famine begins in Ireland"],
  [1846, "Neptune is discovered"],
  [1846, "The Corn Laws are repealed"],
  [1846, "The Mexican–American War begins"],
  [1847, "Charlotte Brontë publishes Jane Eyre"],
  [1847, "Emily Brontë publishes Wuthering Heights"],
  [1848, "Louis-Napoléon Bonaparte is elected President of France"],
  [1848, "Revolutions sweep across Europe; the Communist Manifesto is published"],
  [1848, "The California Gold Rush begins"],
  [1848, "The Chartists' last great rally on Kennington Common"],
  [1848, "The Pre-Raphaelite Brotherhood is founded"],
  [1849, "Britain annexes the Punjab"],
  [1849, "Edgar Allan Poe dies"],
  [1850, "Robert Peel dies after a riding accident"],
  [1850, "Wordsworth dies"],
  [1851, "Gold is discovered in Australia"],
  [1851, "J. M. W. Turner dies"],
  [1851, "Louis-Napoléon seizes power in a coup"],
  [1851, "The Great Exhibition opens in the Crystal Palace"],
  [1851, "The Taiping Rebellion begins in China (approximately)"],
  [1852, "Napoleon III proclaims the Second French Empire"],
  [1852, "The Duke of Wellington dies"],
  [1853, "Commodore Perry's black ships arrive in Japan"],
  [1853, "Compulsory smallpox vaccination is introduced in England"],
  [1853, "Russia destroys the Ottoman fleet at Sinop"],
  [1854, "Florence Nightingale arrives at Scutari"],
  [1854, "John Snow traces a cholera outbreak to the Broad Street pump"],
  [1854, "Oscar Wilde is born in Dublin"],
  [1854, "The Battle of Inkerman"],
  [1854, "The Battle of the Alma"],
  [1854, "The Charge of the Light Brigade at Balaclava"],
  [1855, "Sevastopol falls to the Allies"],
  [1855, "Tsar Nicholas I dies"],
  [1856, "Sigmund Freud is born"],
  [1856, "The Treaty of Paris ends the Crimean War"],
  [1856, "The Victoria Cross is instituted"],
  [1857, "The Indian Rebellion breaks out at Meerut"],
  [1857, "The Siege of Lucknow"],
  [1857, "The massacre at Cawnpore"],
  [1858, "The British Crown takes direct rule of India"],
  [1858, "The Great Stink of London"],
  [1858, "The first transatlantic telegraph cable is laid"],
  [1859, "Arthur Conan Doyle is born in Edinburgh"],
  [1859, "Big Ben's bell begins ringing at Westminster"],
  [1859, "Darwin publishes On the Origin of Species"],
  [1859, "Isambard Kingdom Brunel dies"],
  [1859, "John Brown raids Harpers Ferry"],
  [1859, "John Stuart Mill publishes On Liberty"],
  [1859, "The Battle of Solferino"],
  [1860, "British and French troops loot the Old Summer Palace in Beijing"],
  [1860, "Garibaldi lands in Sicily with his Thousand"],
  [1860, "Lincoln is elected President"],
  [1860, "The Oxford evolution debate between Huxley and Wilberforce"],
  [1861, "Prince Albert dies"],
  [1861, "The First Battle of Bull Run"],
  [1861, "The Kingdom of Italy is proclaimed"],
  [1861, "Tsar Alexander II emancipates the Russian serfs"],
  [1862, "Bismarck becomes Minister President of Prussia"],
  [1862, "The Battle of Antietam"],
  [1863, "Lincoln delivers the Gettysburg Address"],
  [1863, "Lincoln issues the Emancipation Proclamation"],
  [1863, "The Battle of Gettysburg"],
  [1863, "The Football Association is founded"],
  [1863, "The first section of the London Underground opens"],
  [1863, "William Makepeace Thackeray dies"],
  [1864, "Prussia and Austria defeat Denmark"],
  [1864, "Sherman marches through Georgia to the sea"],
  [1864, "The first Geneva Convention is signed"],
  [1865, "Abraham Lincoln is assassinated"],
  [1865, "Lee surrenders at Appomattox"],
  [1865, "Lewis Carroll publishes Alice's Adventures in Wonderland"],
  [1865, "Rudyard Kipling is born in Bombay"],
  [1865, "The Matterhorn is first climbed"],
  [1865, "The Salvation Army is founded"],
  [1866, "Prussia defeats Austria at Königgrätz"],
  [1866, "The transatlantic telegraph cable finally works reliably"],
  [1867, "Canadian Confederation"],
  [1867, "Marx publishes the first volume of Das Kapital"],
  [1867, "Russia sells Alaska to the United States"],
  [1867, "The Emperor Maximilian of Mexico is executed"],
  [1867, "The Second Reform Act"],
  [1868, "Gladstone becomes Prime Minister for the first time"],
  [1868, "The Meiji Restoration in Japan"],
  [1868, "The first Trades Union Congress meets"],
  [1868, "The last public hanging in Britain"],
  [1869, "Mahatma Gandhi is born"],
  [1869, "Mendeleev publishes his periodic table"],
  [1869, "The Cutty Sark is launched"],
  [1869, "The Suez Canal opens"],
  [1869, "The US transcontinental railroad is completed"],
  [1870, "Charles Dickens dies"],
  [1870, "Lenin is born"],
  [1870, "Napoleon III is captured at Sedan"],
  [1870, "The Forster Education Act"],
  [1871, "Rome becomes the capital of Italy"],
  [1871, "Stanley finds Livingstone at Ujiji"],
  [1871, "The German Empire is proclaimed in the Hall of Mirrors at Versailles"],
  [1871, "The Great Chicago Fire"],
  [1871, "Trade unions are legalised in Britain"],
  [1872, "The Mary Celeste is found abandoned"],
  [1872, "The first international football match: Scotland v England"],
  [1872, "The secret ballot is introduced in Britain"],
  [1873, "David Livingstone dies in Africa"],
  [1874, "Disraeli becomes Prime Minister"],
  [1874, "The first Impressionist exhibition is held in Paris"],
  [1874, "Winston Churchill is born at Blenheim Palace"],
  [1875, "Disraeli buys Britain a stake in the Suez Canal"],
  [1876, "Alexander Graham Bell patents the telephone"],
  [1876, "Custer's command is wiped out at the Little Bighorn"],
  [1876, "Parliament makes Queen Victoria Empress of India"],
  [1877, "Edison invents the phonograph"],
  [1877, "The first Wimbledon Championships"],
  [1878, "The Congress of Berlin"],
  [1878, "The Thames pleasure steamer Princess Alice sinks"],
  [1879, "Albert Einstein is born in Ulm"],
  [1879, "Edison demonstrates a practical light bulb"],
  [1879, "The Tay Bridge collapses under a train"],
  [1879, "The Zulu army defeats the British at Isandlwana"],
  [1879, "The defence of Rorke's Drift"],
  [1880, "Ned Kelly is hanged in Melbourne"],
  [1880, "The First Boer War begins"],
  [1881, "The Boers defeat the British at Majuba Hill"],
  [1881, "The gunfight at the O.K. Corral"],
  [1881, "Tsar Alexander II is assassinated"],
  [1882, "Britain occupies Egypt after Tel el-Kebir"],
  [1882, "Charles Darwin dies"],
  [1882, "Robert Koch identifies the tuberculosis bacterium"],
  [1882, "The Phoenix Park murders in Dublin"],
  [1883, "Karl Marx dies in London"],
  [1883, "Krakatoa erupts"],
  [1883, "Richard Wagner dies in Venice"],
  [1884, "The Berlin Conference opens to carve up Africa"],
  [1884, "The Greenwich Meridian is adopted as the prime meridian"],
  [1884, "The Third Reform Act"],
  [1885, "General Gordon is killed at Khartoum"],
  [1885, "Karl Benz builds the first practical motor car"],
  [1885, "The Canadian Pacific Railway is completed"],
  [1886, "Gladstone's first Irish Home Rule Bill is defeated"],
  [1886, "The Statue of Liberty is dedicated"],
  [1887, "Bloody Sunday in Trafalgar Square"],
  [1887, "Queen Victoria's Golden Jubilee"],
  [1888, "The Football League is founded"],
  [1888, "The London matchgirls' strike"],
  [1888, "The Whitechapel murders attributed to Jack the Ripper"],
  [1888, "Wilhelm II becomes German Emperor"],
  [1889, "Adolf Hitler is born in Austria"],
  [1889, "The Eiffel Tower opens"],
  [1889, "The London Dock Strike"],
  [1889, "The Mayerling incident: Crown Prince Rudolf dies"],
  [1890, "Charles de Gaulle is born"],
  [1890, "Kaiser Wilhelm II dismisses Bismarck"],
  [1890, "The Forth Bridge opens"],
  [1890, "The Wounded Knee Massacre"],
  [1890, "Vincent van Gogh dies"],
  [1891, "Charles Stewart Parnell dies"],
  [1892, "Alfred, Lord Tennyson dies"],
  [1892, "Keir Hardie is elected to Parliament"],
  [1893, "Mao Zedong is born"],
  [1893, "New Zealand gives women the vote"],
  [1893, "The Independent Labour Party is founded"],
  [1894, "Alfred Dreyfus is wrongly convicted of treason in France"],
  [1894, "The First Sino-Japanese War begins"],
  [1894, "Tower Bridge opens"],
  [1895, "Oscar Wilde is convicted and imprisoned"],
  [1895, "Röntgen discovers X-rays"],
  [1895, "The Lumière brothers screen the first films to a paying audience"],
  [1896, "Ethiopia defeats Italy at the Battle of Adwa"],
  [1896, "Marconi patents his wireless telegraphy in Britain"],
  [1896, "The first modern Olympic Games are held in Athens"],
  [1897, "Bram Stoker publishes Dracula"],
  [1897, "Queen Victoria's Diamond Jubilee"],
  [1898, "Gladstone dies"],
  [1898, "Kitchener wins the Battle of Omdurman"],
  [1898, "Lewis Carroll dies"],
  [1898, "Otto von Bismarck dies"],
  [1898, "The Fashoda Incident"],
  [1898, "The USS Maine explodes in Havana harbour"],
  [1898, "Émile Zola publishes 'J'accuse…!'"],
  [1899, "Black Week: three British defeats in the Boer War"],
  [1899, "The Second Boer War begins"],
  [1899, "The Siege of Mafeking begins"],

  // ---- 1900 onwards ----
  [1900, "Arthur Evans begins excavating Knossos"],
  [1900, "Oscar Wilde dies in Paris"],
  [1900, "The Boxer Rebellion besieges the foreign legations in Peking"],
  [1900, "The Labour Representation Committee is founded"],
  [1900, "The Relief of Mafeking sparks wild celebrations in Britain"],
  [1901, "President McKinley is assassinated"],
  [1901, "Queen Victoria dies"],
  [1901, "The Commonwealth of Australia is established"],
  [1902, "Mount Pelée destroys the town of Saint-Pierre in Martinique"],
  [1902, "The Anglo-Japanese Alliance is signed"],
  [1902, "The Treaty of Vereeniging ends the Second Boer War"],
  [1903, "Emmeline Pankhurst founds the Women's Social and Political Union"],
  [1903, "The Russian Social Democrats split into Bolsheviks and Mensheviks"],
  [1903, "The Wright brothers make the first powered flight"],
  [1903, "The first Tour de France is held"],
  [1904, "The Entente Cordiale is signed between Britain and France"],
  [1904, "The Russo-Japanese War begins"],
  [1905, "Bloody Sunday in St Petersburg"],
  [1905, "Einstein publishes his special theory of relativity"],
  [1905, "The Japanese destroy the Russian fleet at Tsushima"],
  [1905, "The mutiny on the battleship Potemkin"],
  [1906, "Alfred Dreyfus is exonerated"],
  [1906, "HMS Dreadnought is launched"],
  [1906, "The Liberals win a landslide general election"],
  [1906, "The San Francisco earthquake"],
  [1907, "Baden-Powell holds the first Scout camp on Brownsea Island"],
  [1907, "The Anglo-Russian Convention completes the Triple Entente"],
  [1908, "Austria-Hungary annexes Bosnia"],
  [1908, "Henry Ford launches the Model T"],
  [1908, "London hosts the Olympic Games for the first time"],
  [1908, "Old age pensions are introduced in Britain"],
  [1908, "The Tunguska event flattens a Siberian forest"],
  [1909, "Lloyd George presents his People's Budget"],
  [1909, "Louis Blériot flies across the Channel"],
  [1909, "Robert Peary claims to have reached the North Pole"],
  [1910, "Dr Crippen is arrested at sea after a wireless message"],
  [1910, "Edward VII dies"],
  [1910, "Florence Nightingale dies"],
  [1910, "Leo Tolstoy dies"],
  [1910, "Portugal becomes a republic"],
  [1910, "The Union of South Africa is formed"],
  [1911, "Amundsen reaches the South Pole"],
  [1911, "George V is crowned"],
  [1911, "The Mona Lisa is stolen from the Louvre"],
  [1911, "The Parliament Act curbs the House of Lords"],
  [1911, "The Siege of Sidney Street"],
  [1911, "The Xinhai Revolution overthrows the Qing dynasty"],
  [1912, "RMS Titanic sinks on her maiden voyage"],
  [1912, "Scott's party dies returning from the South Pole"],
  [1912, "The First Balkan War breaks out"],
  [1913, "Suffragette Emily Davison is struck by the King's horse at the Derby"],
  [1913, "Woodrow Wilson becomes US President"],
  [1914, "Archduke Franz Ferdinand is assassinated in Sarajevo"],
  [1914, "Britain declares war on Germany"],
  [1914, "The Christmas truce on the Western Front"],
  [1914, "The First Battle of the Marne"],
  [1914, "The Germans crush the Russians at Tannenberg"],
  [1914, "The Panama Canal opens"],
  [1915, "Allied troops land at Gallipoli"],
  [1915, "Nurse Edith Cavell is executed in Brussels"],
  [1915, "Poison gas is first used on a large scale at Ypres"],
  [1915, "The Armenian Genocide begins"],
  [1915, "The Lusitania is sunk by a German U-boat"],
  [1916, "Lloyd George becomes Prime Minister"],
  [1916, "Lord Kitchener drowns when HMS Hampshire sinks"],
  [1916, "Rasputin is murdered"],
  [1916, "Tanks go into battle for the first time"],
  [1916, "The Battle of Jutland"],
  [1916, "The Battle of Verdun begins"],
  [1916, "The Easter Rising in Dublin"],
  [1916, "The first day of the Battle of the Somme"],
  [1917, "The Balfour Declaration"],
  [1917, "The Battle of Passchendaele"],
  [1917, "The Bolsheviks seize power in the October Revolution"],
  [1917, "The Halifax Explosion devastates the Nova Scotia port"],
  [1917, "The United States enters the First World War"],
  [1917, "The royal family changes its name to Windsor"],
  [1917, "Tsar Nicholas II abdicates"],
  [1918, "The Armistice ends fighting on the Western Front"],
  [1918, "The Kaiser abdicates"],
  [1918, "The Romanovs are executed at Yekaterinburg"],
  [1918, "The Royal Air Force is formed"],
  [1918, "The Spanish flu pandemic spreads worldwide"],
  [1918, "The Treaty of Brest-Litovsk takes Russia out of the war"],
  [1918, "Women over thirty get the vote in Britain"],
  [1919, "Alcock and Brown make the first non-stop transatlantic flight"],
  [1919, "Nancy Astor becomes the first woman to take her seat as an MP"],
  [1919, "The Amritsar massacre"],
  [1919, "The German fleet is scuttled at Scapa Flow"],
  [1919, "The Irish War of Independence begins"],
  [1919, "The Treaty of Versailles is signed"],
  [1920, "Bloody Sunday at Croke Park"],
  [1920, "Prohibition begins in the United States"],
  [1920, "The League of Nations holds its first meeting"],
  [1920, "The Unknown Warrior is buried in Westminster Abbey"],
  [1921, "Marie Stopes opens Britain's first birth control clinic"],
  [1921, "The Anglo-Irish Treaty is signed"],
  [1922, "Howard Carter discovers the tomb of Tutankhamun"],
  [1922, "Michael Collins is killed in an ambush"],
  [1922, "Mussolini's March on Rome"],
  [1922, "The BBC makes its first broadcast"],
  [1922, "The Irish Civil War begins"],
  [1922, "The Ottoman sultanate is abolished"],
  [1922, "The Soviet Union is formed"],
  [1923, "Hitler's Beer Hall Putsch fails in Munich"],
  [1923, "Hyperinflation devastates Germany"],
  [1923, "The Republic of Turkey is proclaimed"],
  [1923, "The first FA Cup Final is played at Wembley"],
  [1924, "Lenin dies"],
  [1924, "Mallory and Irvine vanish near the summit of Everest"],
  [1924, "The first Labour government takes office"],
  [1925, "Churchill returns Britain to the gold standard"],
  [1925, "Hitler publishes the first volume of Mein Kampf"],
  [1925, "Margaret Thatcher is born in Grantham"],
  [1925, "The Scopes 'Monkey Trial' in Tennessee"],
  [1926, "John Logie Baird demonstrates television"],
  [1926, "Princess Elizabeth, the future Elizabeth II, is born"],
  [1926, "The General Strike in Britain"],
  [1927, "Lindbergh flies solo across the Atlantic"],
  [1928, "Alexander Fleming discovers penicillin"],
  [1928, "Emmeline Pankhurst dies"],
  [1928, "Stalin launches the first Five-Year Plan"],
  [1928, "Women gain the vote on equal terms with men in Britain"],
  [1929, "The Lateran Treaty creates Vatican City"],
  [1929, "The St Valentine's Day Massacre in Chicago"],
  [1929, "The Wall Street Crash"],
  [1930, "Arthur Conan Doyle dies"],
  [1930, "Gandhi leads the Salt March"],
  [1930, "Pluto is discovered"],
  [1930, "The airship R101 crashes in France"],
  [1931, "Japan invades Manchuria"],
  [1931, "Ramsay MacDonald forms the National Government"],
  [1931, "The Empire State Building opens"],
  [1931, "The Invergordon Mutiny"],
  [1932, "Oswald Mosley founds the British Union of Fascists"],
  [1932, "The Kinder Scout mass trespass"],
  [1932, "The neutron is discovered by James Chadwick"],
  [1933, "Adolf Hitler becomes Chancellor of Germany"],
  [1933, "Franklin D. Roosevelt launches the New Deal"],
  [1933, "The Oxford Union votes it will not fight 'for King and Country'"],
  [1933, "The Reichstag fire"],
  [1934, "Hitler becomes Führer on the death of Hindenburg"],
  [1934, "Mao's Red Army begins the Long March"],
  [1934, "The Night of the Long Knives"],
  [1935, "George V's Silver Jubilee"],
  [1935, "Italy invades Abyssinia"],
  [1935, "The Nuremberg Laws are enacted"],
  [1936, "Edward VIII abdicates the throne"],
  [1936, "George V dies"],
  [1936, "Germany remilitarises the Rhineland"],
  [1936, "Rudyard Kipling dies"],
  [1936, "The Battle of Cable Street"],
  [1936, "The Berlin Olympics; Jesse Owens wins four golds"],
  [1936, "The Crystal Palace burns down"],
  [1936, "The Jarrow March to London"],
  [1936, "The Spanish Civil War begins"],
  [1937, "George VI is crowned"],
  [1937, "Japan launches full-scale war on China; the Nanjing Massacre follows"],
  [1937, "Neville Chamberlain becomes Prime Minister"],
  [1937, "The German Condor Legion bombs Guernica"],
  [1937, "The Hindenburg airship bursts into flames"],
  [1938, "Chamberlain signs the Munich Agreement"],
  [1938, "Germany annexes Austria in the Anschluss"],
  [1938, "Kristallnacht"],
  [1938, "The Kindertransport begins"],
  [1938, "The locomotive Mallard sets the world steam speed record"],
  [1939, "Britain and France declare war on Germany"],
  [1939, "Germany invades Poland"],
  [1939, "Sigmund Freud dies in London"],
  [1939, "The Battle of the River Plate"],
  [1939, "The Nazi-Soviet Pact is signed"],
  [1939, "The Soviet Union invades Finland"],
  [1940, "Churchill becomes Prime Minister"],
  [1940, "Coventry is devastated by the Luftwaffe"],
  [1940, "France surrenders to Germany"],
  [1940, "Germany occupies the Channel Islands"],
  [1940, "The Blitz on London begins"],
  [1940, "The evacuation of Dunkirk"],
  [1940, "Trotsky is murdered in Mexico"],
  [1941, "Germany launches Operation Barbarossa against the Soviet Union"],
  [1941, "Japan attacks Pearl Harbor"],
  [1941, "Rudolf Hess flies to Scotland"],
  [1941, "The Bismarck is sunk"],
  [1941, "The Germans are halted before Moscow"],
  [1941, "The Siege of Leningrad begins"],
  [1942, "Montgomery's Eighth Army wins the Second Battle of El Alamein"],
  [1942, "Singapore falls to the Japanese"],
  [1942, "The Baedeker raids on historic English cities"],
  [1942, "The Beveridge Report is published"],
  [1942, "The Dieppe Raid"],
  [1942, "The US Navy wins the Battle of Midway"],
  [1942, "The Wannsee Conference plans the Holocaust"],
  [1943, "Mussolini is deposed"],
  [1943, "The Allies invade Sicily"],
  [1943, "The Battle of Kursk"],
  [1943, "The Bengal famine"],
  [1943, "The Dambusters raid"],
  [1943, "The German Sixth Army surrenders at Stalingrad"],
  [1943, "The Tehran Conference"],
  [1943, "The Warsaw Ghetto Uprising"],
  [1944, "Operation Market Garden fails at Arnhem"],
  [1944, "Paris is liberated"],
  [1944, "The Battle of Monte Cassino"],
  [1944, "The Battle of the Bulge begins"],
  [1944, "The D-Day landings in Normandy"],
  [1944, "The Education Act introduces free secondary schooling for all"],
  [1944, "The July Plot to assassinate Hitler fails"],
  [1944, "The Warsaw Uprising"],
  [1944, "The first V-1 flying bombs hit London"],
  [1945, "Auschwitz is liberated by the Red Army"],
  [1945, "Dresden is firebombed"],
  [1945, "Hitler kills himself in his Berlin bunker"],
  [1945, "Japan surrenders"],
  [1945, "Labour wins a landslide; Attlee becomes Prime Minister"],
  [1945, "Mussolini is executed by partisans"],
  [1945, "The Nuremberg trials begin"],
  [1945, "The United Nations is founded"],
  [1945, "The Yalta Conference"],
  [1945, "The atomic bomb is dropped on Hiroshima"],
  [1945, "Victory in Europe Day"],
  [1946, "Churchill's 'Iron Curtain' speech at Fulton, Missouri"],
  [1946, "The King David Hotel bombing in Jerusalem"],
  [1947, "Britain's coal industry is nationalised"],
  [1947, "India and Pakistan gain independence"],
  [1947, "Princess Elizabeth marries Philip Mountbatten"],
  [1947, "The Marshall Plan is announced"],
  [1947, "The Truman Doctrine is proclaimed"],
  [1948, "Gandhi is assassinated"],
  [1948, "London hosts the 'Austerity Olympics'"],
  [1948, "The Berlin Airlift begins"],
  [1948, "The Communist coup in Czechoslovakia"],
  [1948, "The Empire Windrush arrives at Tilbury"],
  [1948, "The National Health Service is founded"],
  [1948, "The State of Israel is proclaimed"],
  [1949, "Germany is divided into East and West"],
  [1949, "Ireland leaves the Commonwealth as a republic"],
  [1949, "Mao proclaims the People's Republic of China"],
  [1949, "NATO is founded"],
  [1949, "Orwell publishes Nineteen Eighty-Four"],
  [1949, "The Soviet Union tests its first atomic bomb"],
  [1950, "George Orwell dies"],
  [1950, "Scottish students take the Stone of Scone from Westminster Abbey"],
  [1950, "The Korean War begins"],
  [1951, "Burgess and Maclean defect to Moscow"],
  [1951, "The Festival of Britain"],
  [1952, "Britain tests its first atomic bomb"],
  [1952, "George VI dies"],
  [1952, "The Great Smog of London"],
  [1952, "The Mau Mau uprising leads to a state of emergency in Kenya"],
  [1953, "Crick and Watson describe the double helix structure of DNA"],
  [1953, "Hillary and Tenzing reach the summit of Everest"],
  [1953, "Stalin dies"],
  [1953, "The Korean War armistice is signed"],
  [1954, "Food rationing ends in Britain"],
  [1954, "Roger Bannister runs the first sub-four-minute mile"],
  [1954, "The French are defeated at Dien Bien Phu"],
  [1955, "Albert Einstein dies"],
  [1955, "Churchill retires as Prime Minister"],
  [1955, "Rosa Parks refuses to give up her bus seat"],
  [1955, "Ruth Ellis is the last woman hanged in Britain"],
  [1955, "The Warsaw Pact is formed"],
  [1956, "Britain's first nuclear power station opens at Calder Hall"],
  [1956, "Khrushchev denounces Stalin in his Secret Speech"],
  [1956, "Soviet tanks crush the Hungarian Revolution"],
  [1956, "The Suez Crisis"],
  [1957, "Ghana becomes independent"],
  [1957, "Macmillan tells Britain it has 'never had it so good'"],
  [1957, "The Soviet Union launches Sputnik"],
  [1957, "The Treaty of Rome founds the European Economic Community"],
  [1957, "The Windscale fire"],
  [1958, "CND holds its first Aldermaston march"],
  [1958, "Charles de Gaulle returns to power in France"],
  [1958, "Race riots break out in Notting Hill"],
  [1958, "The Munich air disaster"],
  [1959, "Fidel Castro takes power in Cuba"],
  [1959, "The Dalai Lama flees Tibet"],
  [1959, "The first stretch of the M1 motorway opens"],
  [1960, "Macmillan's 'Wind of Change' speech"],
  [1960, "National Service call-ups end in Britain"],
  [1960, "Penguin is acquitted in the Lady Chatterley trial"],
  [1960, "The Sharpeville massacre"],
  [1960, "The U-2 spy plane incident"],
  [1961, "The Bay of Pigs invasion"],
  [1961, "The Berlin Wall is built"],
  [1961, "Yuri Gagarin becomes the first human in space"],
  [1962, "Algeria wins independence from France"],
  [1962, "Macmillan's 'Night of the Long Knives' reshuffle"],
  [1962, "The Cuban Missile Crisis"],
  [1963, "Beeching's report cuts Britain's railways"],
  [1963, "De Gaulle vetoes Britain's entry to the EEC"],
  [1963, "Kim Philby defects to Moscow"],
  [1963, "Martin Luther King delivers 'I Have a Dream'"],
  [1963, "President Kennedy is assassinated in Dallas"],
  [1963, "The Great Train Robbery"],
  [1964, "Harold Wilson becomes Prime Minister"],
  [1964, "Khrushchev is ousted"],
  [1964, "Nelson Mandela is sentenced to life imprisonment"],
  [1965, "Rhodesia declares independence unilaterally"],
  [1965, "The death penalty for murder is suspended in Britain"],
  [1965, "Winston Churchill's state funeral"],
  [1966, "Mao launches the Cultural Revolution"],
  [1966, "The Aberfan disaster"],
  [1967, "Che Guevara is killed in Bolivia"],
  [1967, "Homosexuality is partially decriminalised in England and Wales"],
  [1967, "The Six-Day War"],
  [1967, "Wilson devalues the pound"],
  [1968, "Enoch Powell's 'Rivers of Blood' speech"],
  [1968, "Martin Luther King is assassinated"],
  [1968, "Robert Kennedy is assassinated"],
  [1968, "Student revolt and strikes paralyse France"],
  [1968, "The Tet Offensive"],
  [1968, "Warsaw Pact troops end the Prague Spring"],
  [1969, "Apollo 11 lands on the Moon"],
  [1969, "British troops are deployed to Northern Ireland"],
  [1969, "Charles is invested as Prince of Wales at Caernarfon"],
  [1969, "Concorde makes its first flight"],
  [1970, "Charles de Gaulle dies"],
  [1970, "Edward Heath becomes Prime Minister"],
  [1970, "The Apollo 13 mission is aborted"],
  [1971, "Bangladesh wins independence"],
  [1971, "Britain converts to decimal currency"],
  [1971, "Internment without trial is introduced in Northern Ireland"],
  [1972, "Bloody Sunday in Derry"],
  [1972, "Nixon visits China"],
  [1972, "The Munich Olympics massacre"],
  [1973, "A coup overthrows Allende in Chile"],
  [1973, "The United Kingdom joins the European Economic Community"],
  [1973, "The United States withdraws its combat troops from Vietnam"],
  [1973, "The Yom Kippur War and the oil crisis"],
  [1974, "Nixon resigns over Watergate"],
  [1974, "The Birmingham pub bombings"],
  [1974, "The Carnation Revolution in Portugal"],
  [1974, "The three-day week in Britain"],
  [1974, "Turkey invades Cyprus"],
  [1975, "Britain votes to stay in the EEC in its first referendum"],
  [1975, "General Franco dies"],
  [1975, "Saigon falls"],
  [1976, "Britain seeks an IMF loan"],
  [1976, "Mao Zedong dies"],
  [1976, "The Soweto uprising"],
  [1977, "Elizabeth II's Silver Jubilee"],
  [1978, "Karol Wojtyła becomes Pope John Paul II"],
  [1978, "The first test-tube baby is born in Oldham"],
  [1979, "Airey Neave is killed by a car bomb at Westminster"],
  [1979, "Lord Mountbatten is killed by the IRA"],
  [1979, "Margaret Thatcher becomes Prime Minister"],
  [1979, "The Iranian Revolution"],
  [1979, "The Winter of Discontent"],
  [1980, "Solidarity is founded in Poland"],
  [1980, "The SAS storm the Iranian Embassy in London"],
  [1981, "Bobby Sands dies on hunger strike"],
  [1981, "Prince Charles marries Lady Diana Spencer"],
  [1981, "Riots break out in Brixton and Toxteth"],
  [1981, "The SDP is founded"],
  [1982, "HMS Sheffield is sunk by an Exocet"],
  [1982, "The Falklands War"],
  [1982, "The Mary Rose is raised"],
  [1983, "The Soviet Union shoots down Korean Air Lines Flight 007"],
  [1983, "The US invades Grenada"],
  [1984, "Indira Gandhi is assassinated"],
  [1984, "The Bhopal disaster"],
  [1984, "The miners' strike begins in Britain"],
  [1984, "WPC Yvonne Fletcher is shot outside the Libyan Embassy"],
  [1985, "Gorbachev becomes Soviet leader"],
  [1985, "The Bradford City stadium fire"],
  [1986, "Spain and Portugal join the EEC"],
  [1986, "The 'Big Bang' deregulates the City of London"],
  [1986, "The Chernobyl nuclear disaster"],
  [1986, "The Space Shuttle Challenger explodes"],
  [1987, "The Enniskillen bombing"],
  [1987, "The Great Storm hits southern England"],
  [1987, "The Herald of Free Enterprise capsizes at Zeebrugge"],
  [1988, "The Lockerbie bombing"],
  [1988, "The Piper Alpha disaster"],
  [1989, "Ceaușescu is overthrown and executed"],
  [1989, "The Berlin Wall falls"],
  [1989, "The Hillsborough disaster"],
  [1989, "The Velvet Revolution in Czechoslovakia"],
  [1989, "Tim Berners-Lee proposes the World Wide Web"],
  [1990, "Germany is reunified"],
  [1990, "Iraq invades Kuwait"],
  [1990, "Nelson Mandela is released from prison"],
  [1990, "The poll tax riots in London"],
  [1991, "The Gulf War"],
  [1991, "The Soviet Union is dissolved"],
  [1991, "The Yugoslav Wars begin"],
  [1992, "Black Wednesday: the pound crashes out of the ERM"],
  [1992, "The Maastricht Treaty is signed"],
  [1992, "Windsor Castle is badly damaged by fire"],
  [1993, "Czechoslovakia splits in two"],
  [1993, "The Oslo Accords are signed"],
  [1994, "Nelson Mandela becomes President of South Africa"],
  [1994, "The Channel Tunnel opens"],
  [1994, "The IRA declares a ceasefire"],
  [1995, "Barings Bank collapses"],
  [1995, "The Dayton Agreement ends the Bosnian War"],
  [1995, "The Srebrenica massacre"],
  [1996, "Dolly the sheep is born"],
  [1996, "The Dunblane massacre"],
  [1997, "Britain hands Hong Kong back to China"],
  [1997, "Diana, Princess of Wales, dies in Paris"],
  [1997, "Scotland and Wales vote for devolution"],
  [1997, "Tony Blair wins a Labour landslide"],
  [1998, "The Good Friday Agreement is signed"],
  [1998, "The Omagh bombing"],
  [1999, "NATO bombs Yugoslavia over Kosovo"],
  [1999, "The Scottish Parliament and Welsh Assembly open"],
  [1999, "The euro is launched as a currency for banks and markets"],
  [2001, "Foot-and-mouth disease devastates British farming"],
  [2001, "The US-led invasion of Afghanistan"],
  [2002, "Euro notes and coins enter circulation"],
  [2003, "Concorde makes its last commercial flight"],
  [2003, "The Human Genome Project is completed"],
  [2003, "The invasion of Iraq"],
  [2004, "Ten countries join the European Union"],
  [2004, "The Indian Ocean tsunami"],
  [2005, "The 7/7 bombings in London"],
  [2005, "The IRA formally ends its armed campaign"],
  [2007, "Northern Rock suffers the first British bank run in over a century"],
  [2007, "Power-sharing is restored at Stormont"],
  [2008, "Barack Obama is elected US President"],
  [2008, "Lehman Brothers collapses"],
  [2010, "The first coalition government since the war takes office in Britain"],
  [2011, "Osama bin Laden is killed"],
  [2011, "The Fukushima nuclear disaster"],
  [2012, "London hosts the Olympic Games for the third time"],
  [2012, "Richard III's remains are found beneath a Leicester car park"],
  [2013, "Margaret Thatcher dies"],
  [2013, "Nelson Mandela dies"],
  [2013, "Pope Benedict XVI resigns"],
  [2014, "Russia annexes Crimea"],
  [2014, "Scotland votes against independence"],
  [2015, "The Paris attacks at the Bataclan"],
  [2016, "The UK votes to leave the European Union"],
  [2022, "Queen Elizabeth II dies at Balmoral"],
];
